/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dynarithmic_twain_DTwainJavaAPI */

#ifndef _Included_com_dynarithmic_twain_DTwainJavaAPI
#define _Included_com_dynarithmic_twain_DTwainJavaAPI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_LoadLibrary
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1LoadLibrary
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_FreeLibrary
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1FreeLibrary
  (JNIEnv *, jobject);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_EnumSources
 * Signature: ()[J
 */
JNIEXPORT jlongArray JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1EnumSources
  (JNIEnv *, jobject);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_IsTwainAvailable
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1IsTwainAvailable
  (JNIEnv *, jobject);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SysInitialize
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SysInitialize
  (JNIEnv *, jobject);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SysDestroy
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SysDestroy
  (JNIEnv *, jobject);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SelectSource
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SelectSource
  (JNIEnv *, jobject);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SelectDefaultSource
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SelectDefaultSource
  (JNIEnv *, jobject);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_GetLastError
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1GetLastError
  (JNIEnv *, jobject);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_GetTwainMode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1GetTwainMode
  (JNIEnv *, jobject);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_IsSessionEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1IsSessionEnabled
  (JNIEnv *, jobject);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_EndTwainSession
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1EndTwainSession
  (JNIEnv *, jobject);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_GetCountry
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1GetCountry
  (JNIEnv *, jobject);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_GetLanguage
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1GetLanguage
  (JNIEnv *, jobject);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_IsMsgNotifyEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1IsMsgNotifyEnabled
  (JNIEnv *, jobject);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_GetTwainHwnd
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1GetTwainHwnd
  (JNIEnv *, jobject);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_IsAcquiring
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1IsAcquiring
  (JNIEnv *, jobject);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_CreateAcquisitionArray
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1CreateAcquisitionArray
  (JNIEnv *, jobject);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_ClearErrorBuffer
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1ClearErrorBuffer
  (JNIEnv *, jobject);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_GetErrorBufferThreshold
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1GetErrorBufferThreshold
  (JNIEnv *, jobject);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_GetTwainAvailability
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1GetTwainAvailability
  (JNIEnv *, jobject);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_GetVersionInfo
 * Signature: ()Lcom/dynarithmic/twain/DTwainVersionInfo;
 */
JNIEXPORT jobject JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1GetVersionInfo
  (JNIEnv *, jobject);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_StartThread
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1StartThread
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_EndThread
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1EndThread
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SetTwainMode
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SetTwainMode
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SetCountry
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SetCountry
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SetLanguage
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SetLanguage
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_EnableMsgNotify
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1EnableMsgNotify
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_OpenSourcesOnSelect
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1OpenSourcesOnSelect
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SetQueryCapSupport
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SetQueryCapSupport
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SetTwainTimeout
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SetTwainTimeout
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SetErrorBufferThreshold
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SetErrorBufferThreshold
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_AppHandlesExceptions
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1AppHandlesExceptions
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SetTwainDSM
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SetTwainDSM
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_OpenSource
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1OpenSource
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_CloseSource
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1CloseSource
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_CloseSourceUI
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1CloseSourceUI
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SetDefaultSource
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SetDefaultSource
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_IsSourceAcquiring
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1IsSourceAcquiring
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_IsSourceOpen
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1IsSourceOpen
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_GetCurrentPageNum
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1GetCurrentPageNum
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_GetMaxAcquisitions
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1GetMaxAcquisitions
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_GetMaxPagesToAcquire
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1GetMaxPagesToAcquire
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_IsUIControllable
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1IsUIControllable
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_IsUIEnabled
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1IsUIEnabled
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_IsIndicatorSupported
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1IsIndicatorSupported
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_IsIndicatorEnabled
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1IsIndicatorEnabled
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_IsThumbnailSupported
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1IsThumbnailSupported
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_IsThumbnailEnabled
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1IsThumbnailEnabled
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_IsDeviceEventSupported
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1IsDeviceEventSupported
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_IsUIOnlySupported
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1IsUIOnlySupported
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_ShowUIOnly
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1ShowUIOnly
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_IsPrinterSupported
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1IsPrinterSupported
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_IsFeederEnabled
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1IsFeederEnabled
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_IsFeederLoaded
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1IsFeederLoaded
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_IsFeederSupported
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1IsFeederSupported
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_IsFeederSensitive
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1IsFeederSensitive
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_FeedPage
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1FeedPage
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_RewindPage
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1RewindPage
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_ClearPage
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1ClearPage
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_IsAutoFeedEnabled
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1IsAutoFeedEnabled
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_IsAutoFeedSupported
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1IsAutoFeedSupported
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_GetFeederFuncs
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1GetFeederFuncs
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_IsPaperDetectable
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1IsPaperDetectable
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_IsDuplexSupported
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1IsDuplexSupported
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_IsDuplexEnabled
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1IsDuplexEnabled
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_IsCustomDSDataSupported
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1IsCustomDSDataSupported
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_ClearPDFText
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1ClearPDFText
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_IsAutoDeskewSupported
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1IsAutoDeskewSupported
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_IsAutoDeskewEnabled
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1IsAutoDeskewEnabled
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_IsAutoBorderDetectSupported
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1IsAutoBorderDetectSupported
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_IsAutoBorderDetectEnabled
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1IsAutoBorderDetectEnabled
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_IsLightPathSupported
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1IsLightPathSupported
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_IsLampSupported
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1IsLampSupported
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_IsLampEnabled
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1IsLampEnabled
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_IsLightSourceSupported
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1IsLightSourceSupported
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_GetMaxRetryAttempts
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1GetMaxRetryAttempts
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_GetCurrentRetryCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1GetCurrentRetryCount
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_IsSkipImageInfoError
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1IsSkipImageInfoError
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_IsExtImageInfoSupported
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1IsExtImageInfoSupported
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_InitExtImageInfo
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1InitExtImageInfo
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_GetExtImageInfo
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1GetExtImageInfo
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_FreeExtImageInfo
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1FreeExtImageInfo
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_FlushAcquiredPages
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1FlushAcquiredPages
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_IsFileSystemSupported
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1IsFileSystemSupported
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_GetBlankPageAutoDetection
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1GetBlankPageAutoDetection
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_IsBlankPageDetectionOn
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1IsBlankPageDetectionOn
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_IsAutoScanEnabled
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1IsAutoScanEnabled
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_IsDeviceOnLine
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1IsDeviceOnLine
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_IsAutoBrightEnabled
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1IsAutoBrightEnabled
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_IsAutoRotateEnabled
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1IsAutoRotateEnabled
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_IsRotationSupported
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1IsRotationSupported
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_IsPatchCapsSupported
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1IsPatchCapsSupported
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_IsPatchDetectEnabled
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1IsPatchDetectEnabled
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SetAllCapsToDefault
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SetAllCapsToDefault
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_EnumSupportedCaps
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1EnumSupportedCaps
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_EnumExtendedCaps
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1EnumExtendedCaps
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_EnumCustomCaps
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1EnumCustomCaps
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_EnumSourceUnits
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1EnumSourceUnits
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_EnumFileXferFormats
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1EnumFileXferFormats
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_EnumCompressionTypes
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1EnumCompressionTypes
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_EnumPrinterStringModes
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1EnumPrinterStringModes
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_EnumTwainPrintersArray
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1EnumTwainPrintersArray
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_EnumOrientations
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1EnumOrientations
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_EnumPaperSizes
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1EnumPaperSizes
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_EnumPixelTypes
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1EnumPixelTypes
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_EnumBitDepths
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1EnumBitDepths
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_EnumJobControls
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1EnumJobControls
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_EnumLightPaths
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1EnumLightPaths
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_EnumLightSources
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1EnumLightSources
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_GetLightSources
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1GetLightSources
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_EnumExtImageInfoTypes
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1EnumExtImageInfoTypes
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_EnumAlarms
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1EnumAlarms
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_EnumNoiseFilters
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1EnumNoiseFilters
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_EnumPatchMaxRetries
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1EnumPatchMaxRetries
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_EnumPatchMaxPriorities
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1EnumPatchMaxPriorities
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_EnumPatchSearchModes
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1EnumPatchSearchModes
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_EnumPatchTimeOutValues
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1EnumPatchTimeOutValues
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_GetPatchPriorities
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1GetPatchPriorities
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_EnumPatchPriorities
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1EnumPatchPriorities
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_EnumTopCameras
 * Signature: (J)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1EnumTopCameras
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_EnumBottomCameras
 * Signature: (J)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1EnumBottomCameras
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_EnumCameras
 * Signature: (J)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1EnumCameras
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_IsCapSupported
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1IsCapSupported
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_IsFileXferSupported
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1IsFileXferSupported
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_EnableIndicator
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1EnableIndicator
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SetMaxAcquisitions
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SetMaxAcquisitions
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SetSourceUnit
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SetSourceUnit
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_GetCapDataType
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1GetCapDataType
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_GetCapArrayType
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1GetCapArrayType
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_IsCompressionSupported
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1IsCompressionSupported
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_IsPrinterEnabled
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1IsPrinterEnabled
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_EnableFeeder
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1EnableFeeder
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_EnablePrinter
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1EnablePrinter
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_EnableThumbnail
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1EnableThumbnail
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_ForceAcquireBitDepth
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1ForceAcquireBitDepth
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SetAvailablePrinters
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SetAvailablePrinters
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SetDeviceNotifications
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SetDeviceNotifications
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SetPrinterStartNumber
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SetPrinterStartNumber
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_EnableAutoFeed
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1EnableAutoFeed
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_EnableDuplex
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1EnableDuplex
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_IsOrientationSupported
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1IsOrientationSupported
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_IsPaperSizeSupported
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1IsPaperSizeSupported
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_IsPixelTypeSupported
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1IsPixelTypeSupported
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SetPDFASCIICompression
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SetPDFASCIICompression
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SetPostScriptType
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SetPostScriptType
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SetPDFJpegQuality
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SetPDFJpegQuality
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SetPDFOrientation
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SetPDFOrientation
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SetTIFFInvert
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SetTIFFInvert
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SetTIFFCompressType
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SetTIFFCompressType
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_IsJobControlSupported
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1IsJobControlSupported
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_EnableJobFileHandling
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1EnableJobFileHandling
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_EnableAutoDeskew
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1EnableAutoDeskew
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_EnableAutoBorderDetect
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1EnableAutoBorderDetect
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SetLightPath
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SetLightPath
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_EnableLamp
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1EnableLamp
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SetMaxRetryAttempts
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SetMaxRetryAttempts
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SetCurrentRetryCount
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SetCurrentRetryCount
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SkipImageInfoError
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SkipImageInfoError
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SetMultipageScanMode
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SetMultipageScanMode
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SetAlarmVolume
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SetAlarmVolume
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_EnableAutoScan
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1EnableAutoScan
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_ClearBuffers
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1ClearBuffers
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SetFeederAlignment
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SetFeederAlignment
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SetFeederOrder
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SetFeederOrder
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SetMaxBuffers
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SetMaxBuffers
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_IsMaxBuffersSupported
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1IsMaxBuffersSupported
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_EnableAutoBright
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1EnableAutoBright
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_EnableAutoRotate
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1EnableAutoRotate
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SetNoiseFilter
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SetNoiseFilter
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SetPixelFlavor
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SetPixelFlavor
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SetRotation
 * Signature: (JD)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SetRotation
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_GetSourceUnit
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1GetSourceUnit
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_GetDeviceNotifications
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1GetDeviceNotifications
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_GetDeviceEvent
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1GetDeviceEvent
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_GetCompressionSize
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1GetCompressionSize
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_EnumTwainPrinters
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1EnumTwainPrinters
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_GetPrinterStartNumber
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1GetPrinterStartNumber
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_GetDuplexType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1GetDuplexType
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_GetLightPath
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1GetLightPath
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_GetAlarmVolume
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1GetAlarmVolume
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_GetBatteryMinutes
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1GetBatteryMinutes
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_GetBatteryPercent
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1GetBatteryPercent
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_GetFeederAlignment
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1GetFeederAlignment
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_GetFeederOrder
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1GetFeederOrder
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_GetMaxBuffers
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1GetMaxBuffers
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_GetNoiseFilter
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1GetNoiseFilter
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_GetPixelFlavor
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1GetPixelFlavor
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_GetRotation
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1GetRotation
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_GetContrast
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1GetContrast
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_GetBrightness
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1GetBrightness
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_GetResolution
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1GetResolution
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_GetCapOperations
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1GetCapOperations
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_EnumContrastValues
 * Signature: (JZ)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1EnumContrastValues
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_EnumBrightnessValues
 * Signature: (JZ)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1EnumBrightnessValues
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_EnumResolutionValues
 * Signature: (JZ)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1EnumResolutionValues
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_EnumMaxBuffers
 * Signature: (JZ)[I
 */
JNIEXPORT jintArray JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1EnumMaxBuffers
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SetCapValuesInt
 * Signature: (JII[I)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SetCapValuesInt
  (JNIEnv *, jobject, jlong, jint, jint, jintArray);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SetCapValuesDouble
 * Signature: (JII[D)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SetCapValuesDouble
  (JNIEnv *, jobject, jlong, jint, jint, jdoubleArray);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SetCapValuesFrame
 * Signature: (JII[Lcom/dynarithmic/twain/DTwainFrame;)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SetCapValuesFrame
  (JNIEnv *, jobject, jlong, jint, jint, jobjectArray);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SetCapValuesString
 * Signature: (JII[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SetCapValuesString
  (JNIEnv *, jobject, jlong, jint, jint, jobjectArray);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SetCapValuesIntEx
 * Signature: (JIII[I)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SetCapValuesIntEx
  (JNIEnv *, jobject, jlong, jint, jint, jint, jintArray);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SetCapValuesDoubleEx
 * Signature: (JIII[D)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SetCapValuesDoubleEx
  (JNIEnv *, jobject, jlong, jint, jint, jint, jdoubleArray);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SetCapValuesFrameEx
 * Signature: (JIII[Lcom/dynarithmic/twain/DTwainFrame;)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SetCapValuesFrameEx
  (JNIEnv *, jobject, jlong, jint, jint, jint, jobjectArray);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SetCapValuesStringEx
 * Signature: (JIII[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SetCapValuesStringEx
  (JNIEnv *, jobject, jlong, jint, jint, jint, jobjectArray);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SetCapValuesIntEx2
 * Signature: (JIIII[I)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SetCapValuesIntEx2
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint, jintArray);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SetCapValuesDoubleEx2
 * Signature: (JIIII[D)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SetCapValuesDoubleEx2
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint, jdoubleArray);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SetCapValuesFrameEx2
 * Signature: (JIIII[Lcom/dynarithmic/twain/DTwainFrame;)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SetCapValuesFrameEx2
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint, jobjectArray);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SetCapValuesStringEx2
 * Signature: (JIIII[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SetCapValuesStringEx2
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint, jobjectArray);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_GetCapValuesInt
 * Signature: (JII)[I
 */
JNIEXPORT jintArray JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1GetCapValuesInt
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_GetCapValuesDouble
 * Signature: (JII)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1GetCapValuesDouble
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_GetCapValuesFrame
 * Signature: (JII)[Lcom/dynarithmic/twain/DTwainFrame;
 */
JNIEXPORT jobjectArray JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1GetCapValuesFrame
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_GetCapValuesString
 * Signature: (JII)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1GetCapValuesString
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_GetCapValuesIntEx
 * Signature: (JIII)[I
 */
JNIEXPORT jintArray JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1GetCapValuesIntEx
  (JNIEnv *, jobject, jlong, jint, jint, jint);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_GetCapValuesDoubleEx
 * Signature: (JIII)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1GetCapValuesDoubleEx
  (JNIEnv *, jobject, jlong, jint, jint, jint);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_GetCapValuesStringEx
 * Signature: (JIII)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1GetCapValuesStringEx
  (JNIEnv *, jobject, jlong, jint, jint, jint);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_GetCapValuesFrameEx
 * Signature: (JIII)[Lcom/dynarithmic/twain/DTwainFrame;
 */
JNIEXPORT jobjectArray JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1GetCapValuesFrameEx
  (JNIEnv *, jobject, jlong, jint, jint, jint);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_GetCapValuesIntEx2
 * Signature: (JIIII)[I
 */
JNIEXPORT jintArray JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1GetCapValuesIntEx2
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_GetCapValuesDoubleEx2
 * Signature: (JIIII)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1GetCapValuesDoubleEx2
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_GetCapValuesStringEx2
 * Signature: (JIIII)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1GetCapValuesStringEx2
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_GetCapValuesFrameEx2
 * Signature: (JIIII)[Lcom/dynarithmic/twain/DTwainFrame;
 */
JNIEXPORT jobjectArray JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1GetCapValuesFrameEx2
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_GetCapContainer
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1GetCapContainer
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SetFileXferFormat
 * Signature: (JIZ)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SetFileXferFormat
  (JNIEnv *, jobject, jlong, jint, jboolean);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SetCompressionType
 * Signature: (JIZ)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SetCompressionType
  (JNIEnv *, jobject, jlong, jint, jboolean);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SetPrinter
 * Signature: (JIZ)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SetPrinter
  (JNIEnv *, jobject, jlong, jint, jboolean);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SetPrinterStringMode
 * Signature: (JIZ)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SetPrinterStringMode
  (JNIEnv *, jobject, jlong, jint, jboolean);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SetOrientation
 * Signature: (JIZ)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SetOrientation
  (JNIEnv *, jobject, jlong, jint, jboolean);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SetPaperSize
 * Signature: (JIZ)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SetPaperSize
  (JNIEnv *, jobject, jlong, jint, jboolean);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SetBitDepth
 * Signature: (JIZ)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SetBitDepth
  (JNIEnv *, jobject, jlong, jint, jboolean);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SetJobControl
 * Signature: (JIZ)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SetJobControl
  (JNIEnv *, jobject, jlong, jint, jboolean);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SetManualDuplexMode
 * Signature: (JIZ)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SetManualDuplexMode
  (JNIEnv *, jobject, jlong, jint, jboolean);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_GetAcquireArea
 * Signature: (JI)Lcom/dynarithmic/twain/DTwainAcquireArea;
 */
JNIEXPORT jobject JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1GetAcquireArea
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SetAcquireArea
 * Signature: (JILcom/dynarithmic/twain/DTwainAcquireArea;)Lcom/dynarithmic/twain/DTwainAcquireArea;
 */
JNIEXPORT jobject JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SetAcquireArea
  (JNIEnv *, jobject, jlong, jint, jobject);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_GetImageInfo
 * Signature: (J)Lcom/dynarithmic/twain/DTwainImageInfo;
 */
JNIEXPORT jobject JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1GetImageInfo
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SetTwainLog
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SetTwainLog
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_AcquireNative
 * Signature: (JIIZZ)Lcom/dynarithmic/twain/DTwainAcquisitionArray;
 */
JNIEXPORT jobject JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1AcquireNative
  (JNIEnv *, jobject, jlong, jint, jint, jboolean, jboolean);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_AcquireBuffered
 * Signature: (JIIZZ)Lcom/dynarithmic/twain/DTwainAcquisitionArray;
 */
JNIEXPORT jobject JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1AcquireBuffered
  (JNIEnv *, jobject, jlong, jint, jint, jboolean, jboolean);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_AcquireFile
 * Signature: (JLjava/lang/String;IIIIZZ)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1AcquireFile
  (JNIEnv *, jobject, jlong, jstring, jint, jint, jint, jint, jboolean, jboolean);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_GetCustomDSData
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1GetCustomDSData
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SetCustomDSData
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SetCustomDSData
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SetAcquireImageScale
 * Signature: (JDD)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SetAcquireImageScale
  (JNIEnv *, jobject, jlong, jdouble, jdouble);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SetPDFPageSize
 * Signature: (JIDD)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SetPDFPageSize
  (JNIEnv *, jobject, jlong, jint, jdouble, jdouble);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_GetAppInfo
 * Signature: ()Lcom/dynarithmic/twain/DTwainAppInfo;
 */
JNIEXPORT jobject JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1GetAppInfo
  (JNIEnv *, jobject);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_GetSourceInfo
 * Signature: (J)Lcom/dynarithmic/twain/DTwainSourceInfo;
 */
JNIEXPORT jobject JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1GetSourceInfo
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_GetAuthor
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1GetAuthor
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SetAuthor
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SetAuthor
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_GetCaption
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1GetCaption
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SetCaption
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SetCaption
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SelectSourceByName
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SelectSourceByName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_GetNameFromCap
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1GetNameFromCap
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_GetCapFromName
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1GetCapFromName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_TwainSave
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1TwainSave
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SetPDFAuthor
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SetPDFAuthor
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SetPDFCreator
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SetPDFCreator
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SetPDFTitle
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SetPDFTitle
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SetPDFSubject
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SetPDFSubject
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SetPDFKeywords
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SetPDFKeywords
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SetPDFEncryption
 * Signature: (JZLjava/lang/String;Ljava/lang/String;IZ)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SetPDFEncryption
  (JNIEnv *, jobject, jlong, jboolean, jstring, jstring, jint, jboolean);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SetPostScriptTitle
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SetPostScriptTitle
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SetPDFPageScale
 * Signature: (JIDD)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SetPDFPageScale
  (JNIEnv *, jobject, jlong, jint, jdouble, jdouble);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_IsDIBBlank
 * Signature: (JD)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1IsDIBBlank
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SetTempFileDirectory
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SetTempFileDirectory
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_GetTempFileDirectory
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1GetTempFileDirectory
  (JNIEnv *, jobject);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_LogMessage
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1LogMessage
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SelectSource2
 * Signature: (Ljava/lang/String;III)J
 */
JNIEXPORT jlong JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SelectSource2
  (JNIEnv *, jobject, jstring, jint, jint, jint);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_GetErrorString
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1GetErrorString
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_AcquireFileEx
 * Signature: (J[Ljava/lang/String;IIIIZZ)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1AcquireFileEx
  (JNIEnv *, jobject, jlong, jobjectArray, jint, jint, jint, jint, jboolean, jboolean);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_GetCurrentAcquiredImage
 * Signature: (J)Lcom/dynarithmic/twain/DTwainImageData;
 */
JNIEXPORT jobject JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1GetCurrentAcquiredImage
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SetBlankPageDetection
 * Signature: (JDIZ)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SetBlankPageDetection
  (JNIEnv *, jobject, jlong, jdouble, jint, jboolean);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SetAcquireArea2
 * Signature: (JLcom/dynarithmic/twain/DTwainAcquireArea;I)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SetAcquireArea2
  (JNIEnv *, jobject, jlong, jobject, jint);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_GetAcquireArea2
 * Signature: (J)Lcom/dynarithmic/twain/DTwainAcquireArea;
 */
JNIEXPORT jobject JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1GetAcquireArea2
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SetAppInfo
 * Signature: (Lcom/dynarithmic/twain/DTwainAppInfo;)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SetAppInfo
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_InitOCRInterface
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1InitOCRInterface
  (JNIEnv *, jobject);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SelectOCREngine
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SelectOCREngine
  (JNIEnv *, jobject);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SelectDefaultOCREngine
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SelectDefaultOCREngine
  (JNIEnv *, jobject);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SelectOCREngineByName
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SelectOCREngineByName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_EnumOCRInterfaces
 * Signature: ()[J
 */
JNIEXPORT jlongArray JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1EnumOCRInterfaces
  (JNIEnv *, jobject);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_EnumOCRSupportedCaps
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1EnumOCRSupportedCaps
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_GetOCRCapValuesInt
 * Signature: (JII)[I
 */
JNIEXPORT jintArray JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1GetOCRCapValuesInt
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_GetOCRCapValuesString
 * Signature: (JII)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1GetOCRCapValuesString
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SetOCRCapValuesInt
 * Signature: (JII[I)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SetOCRCapValuesInt
  (JNIEnv *, jobject, jlong, jint, jint, jintArray);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SetOCRCapValuesString
 * Signature: (JII[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SetOCRCapValuesString
  (JNIEnv *, jobject, jlong, jint, jint, jobjectArray);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_ShutdownOCREngine
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1ShutdownOCREngine
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_IsOCREngineActivated
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1IsOCREngineActivated
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SetPDFOCRConversion
 * Signature: (JIIIII)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SetPDFOCRConversion
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint, jint);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SetPDFOCRMode
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SetPDFOCRMode
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_ExecuteOCR
 * Signature: (JLjava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1ExecuteOCR
  (JNIEnv *, jobject, jlong, jstring, jint, jint);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_GetOCRInfo
 * Signature: (J)Lcom/dynarithmic/twain/DTwainOCRInfo;
 */
JNIEXPORT jobject JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1GetOCRInfo
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_GetOCRText
 * Signature: (JI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1GetOCRText
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_CreateBufferedStripInfo
 * Signature: (J)Lcom/dynarithmic/twain/DTwainBufferedStripInfo;
 */
JNIEXPORT jobject JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1CreateBufferedStripInfo
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_SetBufferedTransferInfo
 * Signature: (JLcom/dynarithmic/twain/DTwainBufferedStripInfo;)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1SetBufferedTransferInfo
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_GetBufferedStripData
 * Signature: (JLcom/dynarithmic/twain/DTwainBufferedStripInfo;)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1GetBufferedStripData
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_EndBufferedTransfer
 * Signature: (JLcom/dynarithmic/twain/DTwainBufferedStripInfo;)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1EndBufferedTransfer
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_dynarithmic_twain_DTwainJavaAPI
 * Method:    DTWAIN_ResetCapValues
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_twain_DTwainJavaAPI_DTWAIN_1ResetCapValues
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
