#   This file is part of the Dynarithmic TWAIN Library (DTWAIN).                          
#   Copyright (c) 2002-2026 Dynarithmic Software.                                         
#                                                                                         
#   Licensed under the Apache License, Version 2.0 (the "License");                       
#   you may not use this file except in compliance with the License.                      
#   You may obtain a copy of the License at                                               
#                                                                                         
#       http://www.apache.org/licenses/LICENSE-2.0                                        
#                                                                                         
#   Unless required by applicable law or agreed to in writing, software                   
#   distributed under the License is distributed on an "AS IS" BASIS,                     
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.              
#   See the License for the specific language governing permissions and                   
#   limitations under the License.                                                        
#                                                                                         
#   FOR ANY PART OF THE COVERED WORK IN WHICH THE COPYRIGHT IS OWNED BY                   
#   DYNARITHMIC SOFTWARE. DYNARITHMIC SOFTWARE DISCLAIMS THE WARRANTY OF NON INFRINGEMENT 
#   OF THIRD PARTY RIGHTS.                                                                
#   
package TwainConstants;
use strict;
use warnings;
use Exporter 'import';

our @EXPORT_OK = qw(
    TWON_PROTOCOLMINOR TWON_PROTOCOLMAJOR TWON_ARRAY TWON_ENUMERATION TWON_ONEVALUE TWON_RANGE TWON_ICONID TWON_DSMID
    TWON_DSMCODEID TWON_DONTCARE8 TWON_DONTCARE16 TWON_DONTCARE32 TWMF_APPOWNS TWMF_DSMOWNS TWMF_DSOWNS TWMF_POINTER
    TWMF_HANDLE TWTY_INT8 TWTY_INT16 TWTY_INT32 TWTY_UINT8 TWTY_UINT16 TWTY_UINT32 TWTY_BOOL
    TWTY_FIX32 TWTY_FRAME TWTY_STR32 TWTY_STR64 TWTY_STR128 TWTY_STR255 TWTY_HANDLE TWAL_ALARM
    TWAL_FEEDERERROR TWAL_FEEDERWARNING TWAL_BARCODE TWAL_DOUBLEFEED TWAL_JAM TWAL_PATCHCODE TWAL_POWER TWAL_SKEW
    TWAS_NONE TWAS_AUTO TWAS_CURRENT TWBCOR_ROT0 TWBCOR_ROT90 TWBCOR_ROT180 TWBCOR_ROT270 TWBCOR_ROTX
    TWBD_HORZ TWBD_VERT TWBD_HORZVERT TWBD_VERTHORZ TWBO_LSBFIRST TWBO_MSBFIRST TWBP_DISABLE TWBP_AUTO
    TWBR_THRESHOLD TWBR_HALFTONE TWBR_CUSTHALFTONE TWBR_DIFFUSION TWBR_DYNAMICTHRESHOLD TWBT_3OF9 TWBT_2OF5INTERLEAVED TWBT_2OF5NONINTERLEAVED
    TWBT_CODE93 TWBT_CODE128 TWBT_UCC128 TWBT_CODABAR TWBT_UPCA TWBT_UPCE TWBT_EAN8 TWBT_EAN13
    TWBT_POSTNET TWBT_PDF417 TWBT_2OF5INDUSTRIAL TWBT_2OF5MATRIX TWBT_2OF5DATALOGIC TWBT_2OF5IATA TWBT_3OF9FULLASCII TWBT_CODABARWITHSTARTSTOP
    TWBT_MAXICODE TWBT_QRCODE TWCP_NONE TWCP_PACKBITS TWCP_GROUP31D TWCP_GROUP31DEOL TWCP_GROUP32D TWCP_GROUP4
    TWCP_JPEG TWCP_LZW TWCP_JBIG TWCP_PNG TWCP_RLE4 TWCP_RLE8 TWCP_BITFIELDS TWCP_ZIP
    TWCP_JPEG2000 TWCS_BOTH TWCS_TOP TWCS_BOTTOM TWDE_CUSTOMEVENTS TWDE_CHECKAUTOMATICCAPTURE TWDE_CHECKBATTERY TWDE_CHECKDEVICEONLINE
    TWDE_CHECKFLASH TWDE_CHECKPOWERSUPPLY TWDE_CHECKRESOLUTION TWDE_DEVICEADDED TWDE_DEVICEOFFLINE TWDE_DEVICEREADY TWDE_DEVICEREMOVED TWDE_IMAGECAPTURED
    TWDE_IMAGEDELETED TWDE_PAPERDOUBLEFEED TWDE_PAPERJAM TWDE_LAMPFAILURE TWDE_POWERSAVE TWDE_POWERSAVENOTIFY TWDR_GET TWDR_SET
    TWDSK_SUCCESS TWDSK_REPORTONLY TWDSK_FAIL TWDSK_DISABLED TWDX_NONE TWDX_1PASSDUPLEX TWDX_2PASSDUPLEX TWFA_NONE
    TWFA_LEFT TWFA_CENTER TWFA_RIGHT TWFE_GENERAL TWFE_PHOTO TWFF_TIFF TWFF_PICT TWFF_BMP
    TWFF_XBM TWFF_JFIF TWFF_FPX TWFF_TIFFMULTI TWFF_PNG TWFF_SPIFF TWFF_EXIF TWFF_PDF
    TWFF_JP2 TWFF_JPX TWFF_DEJAVU TWFF_PDFA TWFF_PDFA2 TWFF_PDFRASTER TWFL_NONE TWFL_OFF
    TWFL_ON TWFL_AUTO TWFL_REDEYE TWFO_FIRSTPAGEFIRST TWFO_LASTPAGEFIRST TWFP_POCKETERROR TWFP_POCKET1 TWFP_POCKET2
    TWFP_POCKET3 TWFP_POCKET4 TWFP_POCKET5 TWFP_POCKET6 TWFP_POCKET7 TWFP_POCKET8 TWFP_POCKET9 TWFP_POCKET10
    TWFP_POCKET11 TWFP_POCKET12 TWFP_POCKET13 TWFP_POCKET14 TWFP_POCKET15 TWFP_POCKET16 TWFR_BOOK TWFR_FANFOLD
    TWFT_RED TWFT_GREEN TWFT_BLUE TWFT_NONE TWFT_WHITE TWFT_CYAN TWFT_MAGENTA TWFT_YELLOW
    TWFT_BLACK TWFY_CAMERA TWFY_CAMERATOP TWFY_CAMERABOTTOM TWFY_CAMERAPREVIEW TWFY_DOMAIN TWFY_HOST TWFY_DIRECTORY
    TWFY_IMAGE TWFY_UNKNOWN TWIA_UNUSED TWIA_FIXED TWIA_LEVEL1 TWIA_LEVEL2 TWIA_LEVEL3 TWIA_LEVEL4
    TWIC_NONE TWIC_LINK TWIC_EMBED TWIF_NONE TWIF_AUTO TWIF_LOWPASS TWIF_BANDPASS TWIF_HIGHPASS
    TWIF_TEXT TWIF_FINELINE TWIM_NONE TWIM_FRONTONTOP TWIM_FRONTONBOTTOM TWIM_FRONTONLEFT TWIM_FRONTONRIGHT TWJC_NONE
    TWJC_JSIC TWJC_JSIS TWJC_JSXC TWJC_JSXS TWJQ_UNKNOWN TWJQ_LOW TWJQ_MEDIUM TWJQ_HIGH
    TWLP_REFLECTIVE TWLP_TRANSMISSIVE TWLS_RED TWLS_GREEN TWLS_BLUE TWLS_NONE TWLS_WHITE TWLS_UV
    TWLS_IR TWMD_MICR TWMD_RAW TWMD_INVALID TWNF_NONE TWNF_AUTO TWNF_LONEPIXEL TWNF_MAJORITYRULE
    TWOR_ROT0 TWOR_ROT90 TWOR_ROT180 TWOR_ROT270 TWOR_PORTRAIT TWOR_LANDSCAPE TWOR_AUTO TWOR_AUTOTEXT
    TWOR_AUTOPICTURE TWOV_NONE TWOV_AUTO TWOV_TOPBOTTOM TWOV_LEFTRIGHT TWOV_ALL TWPA_RGB TWPA_GRAY
    TWPA_CMY TWPC_CHUNKY TWPC_PLANAR TWPCH_PATCH1 TWPCH_PATCH2 TWPCH_PATCH3 TWPCH_PATCH4 TWPCH_PATCH6
    TWPCH_PATCHT TWPF_CHOCOLATE TWPF_VANILLA TWPM_SINGLESTRING TWPM_MULTISTRING TWPM_COMPOUNDSTRING TWPM_IMAGEADDRESSSTRING TWPR_IMPRINTERTOPBEFORE
    TWPR_IMPRINTERTOPAFTER TWPR_IMPRINTERBOTTOMBEFORE TWPR_IMPRINTERBOTTOMAFTER TWPR_ENDORSERTOPBEFORE TWPR_ENDORSERTOPAFTER TWPR_ENDORSERBOTTOMBEFORE TWPR_ENDORSERBOTTOMAFTER TWPF_NORMAL
    TWPF_BOLD TWPF_ITALIC TWPF_LARGESIZE TWPF_SMALLSIZE TWCT_PAGE TWCT_PATCH1 TWCT_PATCH2 TWCT_PATCH3
    TWCT_PATCH4 TWCT_PATCHT TWCT_PATCH6 TWPS_EXTERNAL TWPS_BATTERY TWPT_BW TWPT_GRAY TWPT_RGB
    TWPT_PALETTE TWPT_CMY TWPT_CMYK TWPT_YUV TWPT_YUVK TWPT_CIEXYZ TWPT_LAB TWPT_SRGB
    TWPT_SCRGB TWPT_INFRARED TWSG_NONE TWSG_AUTO TWSG_MANUAL TWFM_POSITIVE TWFM_NEGATIVE TWDF_ULTRASONIC
    TWDF_BYLENGTH TWDF_INFRARED TWUS_LOW TWUS_MEDIUM TWUS_HIGH TWDP_STOP TWDP_STOPANDWAIT TWDP_SOUND
    TWDP_DONOTIMPRINT TWMR_NONE TWMR_VERTICAL TWMR_HORIZONTAL TWJS_444YCBCR TWJS_444RGB TWJS_422 TWJS_421
    TWJS_411 TWJS_420 TWJS_410 TWJS_311 TWPH_NORMAL TWPH_FRAGILE TWPH_THICK TWPH_TRIFOLD
    TWPH_PHOTOGRAPH TWCI_INFO TWCI_WARNING TWCI_ERROR TWCI_WARMUP TWSS_NONE TWSS_A4 TWSS_JISB5
    TWSS_USLETTER TWSS_USLEGAL TWSS_A5 TWSS_ISOB4 TWSS_ISOB6 TWSS_USLEDGER TWSS_USEXECUTIVE TWSS_A3
    TWSS_ISOB3 TWSS_A6 TWSS_C4 TWSS_C5 TWSS_C6 TWSS_4A0 TWSS_2A0 TWSS_A0
    TWSS_A1 TWSS_A2 TWSS_A7 TWSS_A8 TWSS_A9 TWSS_A10 TWSS_ISOB0 TWSS_ISOB1
    TWSS_ISOB2 TWSS_ISOB5 TWSS_ISOB7 TWSS_ISOB8 TWSS_ISOB9 TWSS_ISOB10 TWSS_JISB0 TWSS_JISB1
    TWSS_JISB2 TWSS_JISB3 TWSS_JISB4 TWSS_JISB6 TWSS_JISB7 TWSS_JISB8 TWSS_JISB9 TWSS_JISB10
    TWSS_C0 TWSS_C1 TWSS_C2 TWSS_C3 TWSS_C7 TWSS_C8 TWSS_C9 TWSS_C10
    TWSS_USSTATEMENT TWSS_BUSINESSCARD TWSS_MAXSIZE TWSX_NATIVE TWSX_FILE TWSX_MEMORY TWSX_MEMFILE TWUN_INCHES
    TWUN_CENTIMETERS TWUN_PICAS TWUN_POINTS TWUN_TWIPS TWUN_PIXELS TWUN_MILLIMETERS TWCY_AFGHANISTAN TWCY_ALGERIA
    TWCY_AMERICANSAMOA TWCY_ANDORRA TWCY_ANGOLA TWCY_ANGUILLA TWCY_ANTIGUA TWCY_ARGENTINA TWCY_ARUBA TWCY_ASCENSIONI
    TWCY_AUSTRALIA TWCY_AUSTRIA TWCY_BAHAMAS TWCY_BAHRAIN TWCY_BANGLADESH TWCY_BARBADOS TWCY_BELGIUM TWCY_BELIZE
    TWCY_BENIN TWCY_BERMUDA TWCY_BHUTAN TWCY_BOLIVIA TWCY_BOTSWANA TWCY_BRITAIN TWCY_BRITVIRGINIS TWCY_BRAZIL
    TWCY_BRUNEI TWCY_BULGARIA TWCY_BURKINAFASO TWCY_BURMA TWCY_BURUNDI TWCY_CAMAROON TWCY_CANADA TWCY_CAPEVERDEIS
    TWCY_CAYMANIS TWCY_CENTRALAFREP TWCY_CHAD TWCY_CHILE TWCY_CHINA TWCY_CHRISTMASIS TWCY_COCOSIS TWCY_COLOMBIA
    TWCY_COMOROS TWCY_CONGO TWCY_COOKIS TWCY_COSTARICA TWCY_CUBA TWCY_CYPRUS TWCY_CZECHOSLOVAKIA TWCY_DENMARK
    TWCY_DJIBOUTI TWCY_DOMINICA TWCY_DOMINCANREP TWCY_EASTERIS TWCY_ECUADOR TWCY_EGYPT TWCY_ELSALVADOR TWCY_EQGUINEA
    TWCY_ETHIOPIA TWCY_FALKLANDIS TWCY_FAEROEIS TWCY_FIJIISLANDS TWCY_FINLAND TWCY_FRANCE TWCY_FRANTILLES TWCY_FRGUIANA
    TWCY_FRPOLYNEISA TWCY_FUTANAIS TWCY_GABON TWCY_GAMBIA TWCY_GERMANY TWCY_GHANA TWCY_GIBRALTER TWCY_GREECE
    TWCY_GREENLAND TWCY_GRENADA TWCY_GRENEDINES TWCY_GUADELOUPE TWCY_GUAM TWCY_GUANTANAMOBAY TWCY_GUATEMALA TWCY_GUINEA
    TWCY_GUINEABISSAU TWCY_GUYANA TWCY_HAITI TWCY_HONDURAS TWCY_HONGKONG TWCY_HUNGARY TWCY_ICELAND TWCY_INDIA
    TWCY_INDONESIA TWCY_IRAN TWCY_IRAQ TWCY_IRELAND TWCY_ISRAEL TWCY_ITALY TWCY_IVORYCOAST TWCY_JAMAICA
    TWCY_JAPAN TWCY_JORDAN TWCY_KENYA TWCY_KIRIBATI TWCY_KOREA TWCY_KUWAIT TWCY_LAOS TWCY_LEBANON
    TWCY_LIBERIA TWCY_LIBYA TWCY_LIECHTENSTEIN TWCY_LUXENBOURG TWCY_MACAO TWCY_MADAGASCAR TWCY_MALAWI TWCY_MALAYSIA
    TWCY_MALDIVES TWCY_MALI TWCY_MALTA TWCY_MARSHALLIS TWCY_MAURITANIA TWCY_MAURITIUS TWCY_MEXICO TWCY_MICRONESIA
    TWCY_MIQUELON TWCY_MONACO TWCY_MONGOLIA TWCY_MONTSERRAT TWCY_MOROCCO TWCY_MOZAMBIQUE TWCY_NAMIBIA TWCY_NAURU
    TWCY_NEPAL TWCY_NETHERLANDS TWCY_NETHANTILLES TWCY_NEVIS TWCY_NEWCALEDONIA TWCY_NEWZEALAND TWCY_NICARAGUA TWCY_NIGER
    TWCY_NIGERIA TWCY_NIUE TWCY_NORFOLKI TWCY_NORWAY TWCY_OMAN TWCY_PAKISTAN TWCY_PALAU TWCY_PANAMA
    TWCY_PARAGUAY TWCY_PERU TWCY_PHILLIPPINES TWCY_PITCAIRNIS TWCY_PNEWGUINEA TWCY_POLAND TWCY_PORTUGAL TWCY_QATAR
    TWCY_REUNIONI TWCY_ROMANIA TWCY_RWANDA TWCY_SAIPAN TWCY_SANMARINO TWCY_SAOTOME TWCY_SAUDIARABIA TWCY_SENEGAL
    TWCY_SEYCHELLESIS TWCY_SIERRALEONE TWCY_SINGAPORE TWCY_SOLOMONIS TWCY_SOMALI TWCY_SOUTHAFRICA TWCY_SPAIN TWCY_SRILANKA
    TWCY_STHELENA TWCY_STKITTS TWCY_STLUCIA TWCY_STPIERRE TWCY_STVINCENT TWCY_SUDAN TWCY_SURINAME TWCY_SWAZILAND
    TWCY_SWEDEN TWCY_SWITZERLAND TWCY_SYRIA TWCY_TAIWAN TWCY_TANZANIA TWCY_THAILAND TWCY_TOBAGO TWCY_TOGO
    TWCY_TONGAIS TWCY_TRINIDAD TWCY_TUNISIA TWCY_TURKEY TWCY_TURKSCAICOS TWCY_TUVALU TWCY_UGANDA TWCY_USSR
    TWCY_UAEMIRATES TWCY_UNITEDKINGDOM TWCY_USA TWCY_URUGUAY TWCY_VANUATU TWCY_VATICANCITY TWCY_VENEZUELA TWCY_WAKE
    TWCY_WALLISIS TWCY_WESTERNSAHARA TWCY_WESTERNSAMOA TWCY_YEMEN TWCY_YUGOSLAVIA TWCY_ZAIRE TWCY_ZAMBIA TWCY_ZIMBABWE
    TWCY_ALBANIA TWCY_ARMENIA TWCY_AZERBAIJAN TWCY_BELARUS TWCY_BOSNIAHERZGO TWCY_CAMBODIA TWCY_CROATIA TWCY_CZECHREPUBLIC
    TWCY_DIEGOGARCIA TWCY_ERITREA TWCY_ESTONIA TWCY_GEORGIA TWCY_LATVIA TWCY_LESOTHO TWCY_LITHUANIA TWCY_MACEDONIA
    TWCY_MAYOTTEIS TWCY_MOLDOVA TWCY_MYANMAR TWCY_NORTHKOREA TWCY_PUERTORICO TWCY_RUSSIA TWCY_SERBIA TWCY_SLOVAKIA
    TWCY_SLOVENIA TWCY_SOUTHKOREA TWCY_UKRAINE TWCY_USVIRGINIS TWCY_VIETNAM TWLG_USERLOCALE TWLG_DAN TWLG_DUT
    TWLG_ENG TWLG_FCF TWLG_FIN TWLG_FRN TWLG_GER TWLG_ICE TWLG_ITN TWLG_NOR
    TWLG_POR TWLG_SPA TWLG_SWE TWLG_USA TWLG_AFRIKAANS TWLG_ALBANIA TWLG_ARABIC TWLG_ARABIC_ALGERIA
    TWLG_ARABIC_BAHRAIN TWLG_ARABIC_EGYPT TWLG_ARABIC_IRAQ TWLG_ARABIC_JORDAN TWLG_ARABIC_KUWAIT TWLG_ARABIC_LEBANON TWLG_ARABIC_LIBYA TWLG_ARABIC_MOROCCO
    TWLG_ARABIC_OMAN TWLG_ARABIC_QATAR TWLG_ARABIC_SAUDIARABIA TWLG_ARABIC_SYRIA TWLG_ARABIC_TUNISIA TWLG_ARABIC_UAE TWLG_ARABIC_YEMEN TWLG_BASQUE
    TWLG_BYELORUSSIAN TWLG_BULGARIAN TWLG_CATALAN TWLG_CHINESE TWLG_CHINESE_HONGKONG TWLG_CHINESE_PRC TWLG_CHINESE_SINGAPORE TWLG_CHINESE_SIMPLIFIED
    TWLG_CHINESE_TAIWAN TWLG_CHINESE_TRADITIONAL TWLG_CROATIA TWLG_CZECH TWLG_DANISH TWLG_DUTCH TWLG_DUTCH_BELGIAN TWLG_ENGLISH
    TWLG_ENGLISH_AUSTRALIAN TWLG_ENGLISH_CANADIAN TWLG_ENGLISH_IRELAND TWLG_ENGLISH_NEWZEALAND TWLG_ENGLISH_SOUTHAFRICA TWLG_ENGLISH_UK TWLG_ENGLISH_USA TWLG_ESTONIAN
    TWLG_FAEROESE TWLG_FARSI TWLG_FINNISH TWLG_FRENCH TWLG_FRENCH_BELGIAN TWLG_FRENCH_CANADIAN TWLG_FRENCH_LUXEMBOURG TWLG_FRENCH_SWISS
    TWLG_GERMAN TWLG_GERMAN_AUSTRIAN TWLG_GERMAN_LUXEMBOURG TWLG_GERMAN_LIECHTENSTEIN TWLG_GERMAN_SWISS TWLG_GREEK TWLG_HEBREW TWLG_HUNGARIAN
    TWLG_ICELANDIC TWLG_INDONESIAN TWLG_ITALIAN TWLG_ITALIAN_SWISS TWLG_JAPANESE TWLG_KOREAN TWLG_KOREAN_JOHAB TWLG_LATVIAN
    TWLG_LITHUANIAN TWLG_NORWEGIAN TWLG_NORWEGIAN_BOKMAL TWLG_NORWEGIAN_NYNORSK TWLG_POLISH TWLG_PORTUGUESE TWLG_PORTUGUESE_BRAZIL TWLG_ROMANIAN
    TWLG_RUSSIAN TWLG_SERBIAN_LATIN TWLG_SLOVAK TWLG_SLOVENIAN TWLG_SPANISH TWLG_SPANISH_MEXICAN TWLG_SPANISH_MODERN TWLG_SWEDISH
    TWLG_THAI TWLG_TURKISH TWLG_UKRANIAN TWLG_ASSAMESE TWLG_BENGALI TWLG_BIHARI TWLG_BODO TWLG_DOGRI
    TWLG_GUJARATI TWLG_HARYANVI TWLG_HINDI TWLG_KANNADA TWLG_KASHMIRI TWLG_MALAYALAM TWLG_MARATHI TWLG_MARWARI
    TWLG_MEGHALAYAN TWLG_MIZO TWLG_NAGA TWLG_ORISSI TWLG_PUNJABI TWLG_PUSHTU TWLG_SERBIAN_CYRILLIC TWLG_SIKKIMI
    TWLG_SWEDISH_FINLAND TWLG_TAMIL TWLG_TELUGU TWLG_TRIPURI TWLG_URDU TWLG_VIETNAMESE DG_CONTROL DG_IMAGE
    DG_AUDIO DF_DSM2 DF_APP2 DF_DS2 DG_MASK DAT_NULL DAT_CUSTOMBASE DAT_CAPABILITY
    DAT_EVENT DAT_IDENTITY DAT_PARENT DAT_PENDINGXFERS DAT_SETUPMEMXFER DAT_SETUPFILEXFER DAT_STATUS DAT_USERINTERFACE
    DAT_XFERGROUP DAT_CUSTOMDSDATA DAT_DEVICEEVENT DAT_FILESYSTEM DAT_PASSTHRU DAT_CALLBACK DAT_STATUSUTF8 DAT_CALLBACK2
    DAT_METRICS DAT_TWAINDIRECT DAT_IMAGEINFO DAT_IMAGELAYOUT DAT_IMAGEMEMXFER DAT_IMAGENATIVEXFER DAT_IMAGEFILEXFER DAT_CIECOLOR
    DAT_GRAYRESPONSE DAT_RGBRESPONSE DAT_JPEGCOMPRESSION DAT_PALETTE8 DAT_EXTIMAGEINFO DAT_FILTER DAT_AUDIOFILEXFER DAT_AUDIOINFO
    DAT_AUDIONATIVEXFER DAT_ICCPROFILE DAT_IMAGEMEMFILEXFER DAT_ENTRYPOINT MSG_NULL MSG_CUSTOMBASE MSG_GET MSG_GETCURRENT
    MSG_GETDEFAULT MSG_GETFIRST MSG_GETNEXT MSG_SET MSG_RESET MSG_QUERYSUPPORT MSG_GETHELP MSG_GETLABEL
    MSG_GETLABELENUM MSG_SETCONSTRAINT MSG_XFERREADY MSG_CLOSEDSREQ MSG_CLOSEDSOK MSG_DEVICEEVENT MSG_OPENDSM MSG_CLOSEDSM
    MSG_OPENDS MSG_CLOSEDS MSG_USERSELECT MSG_DISABLEDS MSG_ENABLEDS MSG_ENABLEDSUIONLY MSG_PROCESSEVENT MSG_ENDXFER
    MSG_STOPFEEDER MSG_CHANGEDIRECTORY MSG_CREATEDIRECTORY MSG_DELETE MSG_FORMATMEDIA MSG_GETCLOSE MSG_GETFIRSTFILE MSG_GETINFO
    MSG_GETNEXTFILE MSG_RENAME MSG_COPY MSG_AUTOMATICCAPTUREDIRECTORY MSG_PASSTHRU MSG_REGISTER_CALLBACK MSG_RESETALL MSG_SETTASK
    CAP_CUSTOMBASE CAP_XFERCOUNT ICAP_COMPRESSION ICAP_PIXELTYPE ICAP_UNITS ICAP_XFERMECH CAP_AUTHOR CAP_CAPTION
    CAP_FEEDERENABLED CAP_FEEDERLOADED CAP_TIMEDATE CAP_SUPPORTEDCAPS CAP_EXTENDEDCAPS CAP_AUTOFEED CAP_CLEARPAGE CAP_FEEDPAGE
    CAP_REWINDPAGE CAP_INDICATORS CAP_PAPERDETECTABLE CAP_UICONTROLLABLE CAP_DEVICEONLINE CAP_AUTOSCAN CAP_THUMBNAILSENABLED CAP_DUPLEX
    CAP_DUPLEXENABLED CAP_ENABLEDSUIONLY CAP_CUSTOMDSDATA CAP_ENDORSER CAP_JOBCONTROL CAP_ALARMS CAP_ALARMVOLUME CAP_AUTOMATICCAPTURE
    CAP_TIMEBEFOREFIRSTCAPTURE CAP_TIMEBETWEENCAPTURES CAP_MAXBATCHBUFFERS CAP_DEVICETIMEDATE CAP_POWERSUPPLY CAP_CAMERAPREVIEWUI CAP_DEVICEEVENT CAP_SERIALNUMBER
    CAP_PRINTER CAP_PRINTERENABLED CAP_PRINTERINDEX CAP_PRINTERMODE CAP_PRINTERSTRING CAP_PRINTERSUFFIX CAP_LANGUAGE CAP_FEEDERALIGNMENT
    CAP_FEEDERORDER CAP_REACQUIREALLOWED CAP_BATTERYMINUTES CAP_BATTERYPERCENTAGE CAP_CAMERASIDE CAP_SEGMENTED CAP_CAMERAENABLED CAP_CAMERAORDER
    CAP_MICRENABLED CAP_FEEDERPREP CAP_FEEDERPOCKET CAP_AUTOMATICSENSEMEDIUM CAP_CUSTOMINTERFACEGUID CAP_SUPPORTEDCAPSSEGMENTUNIQUE CAP_SUPPORTEDDATS CAP_DOUBLEFEEDDETECTION
    CAP_DOUBLEFEEDDETECTIONLENGTH CAP_DOUBLEFEEDDETECTIONSENSITIVITY CAP_DOUBLEFEEDDETECTIONRESPONSE CAP_PAPERHANDLING CAP_INDICATORSMODE CAP_PRINTERVERTICALOFFSET CAP_POWERSAVETIME CAP_PRINTERCHARROTATION
    CAP_PRINTERFONTSTYLE CAP_PRINTERINDEXLEADCHAR CAP_PRINTERINDEXMAXVALUE CAP_PRINTERINDEXNUMDIGITS CAP_PRINTERINDEXSTEP CAP_PRINTERINDEXTRIGGER CAP_PRINTERSTRINGPREVIEW CAP_SHEETCOUNT
    CAP_IMAGEADDRESSENABLED CAP_IAFIELDA_LEVEL CAP_IAFIELDB_LEVEL CAP_IAFIELDC_LEVEL CAP_IAFIELDD_LEVEL CAP_IAFIELDE_LEVEL CAP_IAFIELDA_PRINTFORMAT CAP_IAFIELDB_PRINTFORMAT
    CAP_IAFIELDC_PRINTFORMAT CAP_IAFIELDD_PRINTFORMAT CAP_IAFIELDE_PRINTFORMAT CAP_IAFIELDA_VALUE CAP_IAFIELDB_VALUE CAP_IAFIELDC_VALUE CAP_IAFIELDD_VALUE CAP_IAFIELDE_VALUE
    CAP_IAFIELDA_LASTPAGE CAP_IAFIELDB_LASTPAGE CAP_IAFIELDC_LASTPAGE CAP_IAFIELDD_LASTPAGE CAP_IAFIELDE_LASTPAGE ICAP_AUTOBRIGHT ICAP_BRIGHTNESS ICAP_CONTRAST
    ICAP_CUSTHALFTONE ICAP_EXPOSURETIME ICAP_FILTER ICAP_FLASHUSED ICAP_GAMMA ICAP_HALFTONES ICAP_HIGHLIGHT ICAP_IMAGEFILEFORMAT
    ICAP_LAMPSTATE ICAP_LIGHTSOURCE ICAP_ORIENTATION ICAP_PHYSICALWIDTH ICAP_PHYSICALHEIGHT ICAP_SHADOW ICAP_FRAMES ICAP_XNATIVERESOLUTION
    ICAP_YNATIVERESOLUTION ICAP_XRESOLUTION ICAP_YRESOLUTION ICAP_MAXFRAMES ICAP_TILES ICAP_BITORDER ICAP_CCITTKFACTOR ICAP_LIGHTPATH
    ICAP_PIXELFLAVOR ICAP_PLANARCHUNKY ICAP_ROTATION ICAP_SUPPORTEDSIZES ICAP_THRESHOLD ICAP_XSCALING ICAP_YSCALING ICAP_BITORDERCODES
    ICAP_PIXELFLAVORCODES ICAP_JPEGPIXELTYPE ICAP_TIMEFILL ICAP_BITDEPTH ICAP_BITDEPTHREDUCTION ICAP_UNDEFINEDIMAGESIZE ICAP_IMAGEDATASET ICAP_EXTIMAGEINFO
    ICAP_MINIMUMHEIGHT ICAP_MINIMUMWIDTH ICAP_AUTODISCARDBLANKPAGES ICAP_FLIPROTATION ICAP_BARCODEDETECTIONENABLED ICAP_SUPPORTEDBARCODETYPES ICAP_BARCODEMAXSEARCHPRIORITIES ICAP_BARCODESEARCHPRIORITIES
    ICAP_BARCODESEARCHMODE ICAP_BARCODEMAXRETRIES ICAP_BARCODETIMEOUT ICAP_ZOOMFACTOR ICAP_PATCHCODEDETECTIONENABLED ICAP_SUPPORTEDPATCHCODETYPES ICAP_PATCHCODEMAXSEARCHPRIORITIES ICAP_PATCHCODESEARCHPRIORITIES
    ICAP_PATCHCODESEARCHMODE ICAP_PATCHCODEMAXRETRIES ICAP_PATCHCODETIMEOUT ICAP_FLASHUSED2 ICAP_IMAGEFILTER ICAP_NOISEFILTER ICAP_OVERSCAN ICAP_AUTOMATICBORDERDETECTION
    ICAP_AUTOMATICDESKEW ICAP_AUTOMATICROTATE ICAP_JPEGQUALITY ICAP_FEEDERTYPE ICAP_ICCPROFILE ICAP_AUTOSIZE ICAP_AUTOMATICCROPUSESFRAME ICAP_AUTOMATICLENGTHDETECTION
    ICAP_AUTOMATICCOLORENABLED ICAP_AUTOMATICCOLORNONCOLORPIXELTYPE ICAP_COLORMANAGEMENTENABLED ICAP_IMAGEMERGE ICAP_IMAGEMERGEHEIGHTTHRESHOLD ICAP_SUPPORTEDEXTIMAGEINFO ICAP_FILMTYPE ICAP_MIRROR
    ICAP_JPEGSUBSAMPLING ACAP_XFERMECH TWEI_BARCODEX TWEI_BARCODEY TWEI_BARCODETEXT TWEI_BARCODETYPE TWEI_DESHADETOP TWEI_DESHADELEFT
    TWEI_DESHADEHEIGHT TWEI_DESHADEWIDTH TWEI_DESHADESIZE TWEI_SPECKLESREMOVED TWEI_HORZLINEXCOORD TWEI_HORZLINEYCOORD TWEI_HORZLINELENGTH TWEI_HORZLINETHICKNESS
    TWEI_VERTLINEXCOORD TWEI_VERTLINEYCOORD TWEI_VERTLINELENGTH TWEI_VERTLINETHICKNESS TWEI_PATCHCODE TWEI_ENDORSEDTEXT TWEI_FORMCONFIDENCE TWEI_FORMTEMPLATEMATCH
    TWEI_FORMTEMPLATEPAGEMATCH TWEI_FORMHORZDOCOFFSET TWEI_FORMVERTDOCOFFSET TWEI_BARCODECOUNT TWEI_BARCODECONFIDENCE TWEI_BARCODEROTATION TWEI_BARCODETEXTLENGTH TWEI_DESHADECOUNT
    TWEI_DESHADEBLACKCOUNTOLD TWEI_DESHADEBLACKCOUNTNEW TWEI_DESHADEBLACKRLMIN TWEI_DESHADEBLACKRLMAX TWEI_DESHADEWHITECOUNTOLD TWEI_DESHADEWHITECOUNTNEW TWEI_DESHADEWHITERLMIN TWEI_DESHADEWHITERLAVE
    TWEI_DESHADEWHITERLMAX TWEI_BLACKSPECKLESREMOVED TWEI_WHITESPECKLESREMOVED TWEI_HORZLINECOUNT TWEI_VERTLINECOUNT TWEI_DESKEWSTATUS TWEI_SKEWORIGINALANGLE TWEI_SKEWFINALANGLE
    TWEI_SKEWCONFIDENCE TWEI_SKEWWINDOWX1 TWEI_SKEWWINDOWY1 TWEI_SKEWWINDOWX2 TWEI_SKEWWINDOWY2 TWEI_SKEWWINDOWX3 TWEI_SKEWWINDOWY3 TWEI_SKEWWINDOWX4
    TWEI_SKEWWINDOWY4 TWEI_BOOKNAME TWEI_CHAPTERNUMBER TWEI_DOCUMENTNUMBER TWEI_PAGENUMBER TWEI_CAMERA TWEI_FRAMENUMBER TWEI_FRAME
    TWEI_PIXELFLAVOR TWEI_ICCPROFILE TWEI_LASTSEGMENT TWEI_SEGMENTNUMBER TWEI_MAGDATA TWEI_MAGTYPE TWEI_PAGESIDE TWEI_FILESYSTEMSOURCE
    TWEI_IMAGEMERGED TWEI_MAGDATALENGTH TWEI_PAPERCOUNT TWEI_PRINTERTEXT TWEI_TWAINDIRECTMETADATA TWEI_IAFIELDA_VALUE TWEI_IAFIELDB_VALUE TWEI_IAFIELDC_VALUE
    TWEI_IAFIELDD_VALUE TWEI_IAFIELDE_VALUE TWEI_IALEVEL TWEI_PRINTER TWEI_BARCODETEXT2 TWEJ_NONE TWEJ_MIDSEPARATOR TWEJ_PATCH1
    TWEJ_PATCH2 TWEJ_PATCH3 TWEJ_PATCH4 TWEJ_PATCH6 TWEJ_PATCHT TWRC_CUSTOMBASE TWRC_SUCCESS TWRC_FAILURE
    TWRC_CHECKSTATUS TWRC_CANCEL TWRC_DSEVENT TWRC_NOTDSEVENT TWRC_XFERDONE TWRC_ENDOFLIST TWRC_INFONOTSUPPORTED TWRC_DATANOTAVAILABLE
    TWRC_BUSY TWRC_SCANNERLOCKED TWCC_CUSTOMBASE TWCC_SUCCESS TWCC_BUMMER TWCC_LOWMEMORY TWCC_NODS TWCC_MAXCONNECTIONS
    TWCC_OPERATIONERROR TWCC_BADCAP TWCC_BADPROTOCOL TWCC_BADVALUE TWCC_SEQERROR TWCC_BADDEST TWCC_CAPUNSUPPORTED TWCC_CAPBADOPERATION
    TWCC_CAPSEQERROR TWCC_DENIED TWCC_FILEEXISTS TWCC_FILENOTFOUND TWCC_NOTEMPTY TWCC_PAPERJAM TWCC_PAPERDOUBLEFEED TWCC_FILEWRITEERROR
    TWCC_CHECKDEVICEONLINE TWCC_INTERLOCK TWCC_DAMAGEDCORNER TWCC_FOCUSERROR TWCC_DOCTOOLIGHT TWCC_DOCTOODARK TWCC_NOMEDIA TWQC_GET
    TWQC_SET TWQC_GETDEFAULT TWQC_GETCURRENT TWQC_RESET TWQC_SETCONSTRAINT TWQC_GETHELP TWQC_GETLABEL TWQC_GETLABELENUM
    TWTY_STR1024 TWTY_UNI512 TWFF_JPN DAT_TWUNKIDENTITY DAT_SETUPFILEXFER2 CAP_CLEARBUFFERS CAP_SUPPORTEDCAPSEXT CAP_PAGEMULTIPLEACQUIRE
    CAP_PAPERBINDING CAP_PASSTHRU CAP_POWERDOWNTIME ACAP_AUDIOFILEFORMAT MSG_CHECKSTATUS MSG_INVOKE_CALLBACK TWQC_CONSTRAINABLE TWSX_FILE2
    TWFS_FILESYSTEM TWFS_RECURSIVEDELETE TWPT_SRGB64 TWPT_BGR TWPT_CIELAB TWPT_CIELUV TWPT_YCBCR TWSS_B
    TWSS_A4LETTER TWSS_B3 TWSS_B4 TWSS_B6 TWSS_B5LETTER TWAF_WAV TWAF_AIFF TWAF_AU
    TWAF_SND TWCB_AUTO TWCB_CLEAR TWCB_NOCLEAR
);

use constant TWON_PROTOCOLMINOR => 5;
use constant TWON_PROTOCOLMAJOR => 2;
use constant TWON_ARRAY => 3;
use constant TWON_ENUMERATION => 4;
use constant TWON_ONEVALUE => 5;
use constant TWON_RANGE => 6;
use constant TWON_ICONID => 962;
use constant TWON_DSMID => 461;
use constant TWON_DSMCODEID => 63;
use constant TWON_DONTCARE8 => 255;
use constant TWON_DONTCARE16 => 65535;
use constant TWON_DONTCARE32 => 4294967295;
use constant TWMF_APPOWNS => 1;
use constant TWMF_DSMOWNS => 2;
use constant TWMF_DSOWNS => 4;
use constant TWMF_POINTER => 8;
use constant TWMF_HANDLE => 16;
use constant TWTY_INT8 => 0;
use constant TWTY_INT16 => 1;
use constant TWTY_INT32 => 2;
use constant TWTY_UINT8 => 3;
use constant TWTY_UINT16 => 4;
use constant TWTY_UINT32 => 5;
use constant TWTY_BOOL => 6;
use constant TWTY_FIX32 => 7;
use constant TWTY_FRAME => 8;
use constant TWTY_STR32 => 9;
use constant TWTY_STR64 => 10;
use constant TWTY_STR128 => 11;
use constant TWTY_STR255 => 12;
use constant TWTY_HANDLE => 15;
use constant TWAL_ALARM => 0;
use constant TWAL_FEEDERERROR => 1;
use constant TWAL_FEEDERWARNING => 2;
use constant TWAL_BARCODE => 3;
use constant TWAL_DOUBLEFEED => 4;
use constant TWAL_JAM => 5;
use constant TWAL_PATCHCODE => 6;
use constant TWAL_POWER => 7;
use constant TWAL_SKEW => 8;
use constant TWAS_NONE => 0;
use constant TWAS_AUTO => 1;
use constant TWAS_CURRENT => 2;
use constant TWBCOR_ROT0 => 0;
use constant TWBCOR_ROT90 => 1;
use constant TWBCOR_ROT180 => 2;
use constant TWBCOR_ROT270 => 3;
use constant TWBCOR_ROTX => 4;
use constant TWBD_HORZ => 0;
use constant TWBD_VERT => 1;
use constant TWBD_HORZVERT => 2;
use constant TWBD_VERTHORZ => 3;
use constant TWBO_LSBFIRST => 0;
use constant TWBO_MSBFIRST => 1;
use constant TWBP_DISABLE => -2;
use constant TWBP_AUTO => -1;
use constant TWBR_THRESHOLD => 0;
use constant TWBR_HALFTONE => 1;
use constant TWBR_CUSTHALFTONE => 2;
use constant TWBR_DIFFUSION => 3;
use constant TWBR_DYNAMICTHRESHOLD => 4;
use constant TWBT_3OF9 => 0;
use constant TWBT_2OF5INTERLEAVED => 1;
use constant TWBT_2OF5NONINTERLEAVED => 2;
use constant TWBT_CODE93 => 3;
use constant TWBT_CODE128 => 4;
use constant TWBT_UCC128 => 5;
use constant TWBT_CODABAR => 6;
use constant TWBT_UPCA => 7;
use constant TWBT_UPCE => 8;
use constant TWBT_EAN8 => 9;
use constant TWBT_EAN13 => 10;
use constant TWBT_POSTNET => 11;
use constant TWBT_PDF417 => 12;
use constant TWBT_2OF5INDUSTRIAL => 13;
use constant TWBT_2OF5MATRIX => 14;
use constant TWBT_2OF5DATALOGIC => 15;
use constant TWBT_2OF5IATA => 16;
use constant TWBT_3OF9FULLASCII => 17;
use constant TWBT_CODABARWITHSTARTSTOP => 18;
use constant TWBT_MAXICODE => 19;
use constant TWBT_QRCODE => 20;
use constant TWCP_NONE => 0;
use constant TWCP_PACKBITS => 1;
use constant TWCP_GROUP31D => 2;
use constant TWCP_GROUP31DEOL => 3;
use constant TWCP_GROUP32D => 4;
use constant TWCP_GROUP4 => 5;
use constant TWCP_JPEG => 6;
use constant TWCP_LZW => 7;
use constant TWCP_JBIG => 8;
use constant TWCP_PNG => 9;
use constant TWCP_RLE4 => 10;
use constant TWCP_RLE8 => 11;
use constant TWCP_BITFIELDS => 12;
use constant TWCP_ZIP => 13;
use constant TWCP_JPEG2000 => 14;
use constant TWCS_BOTH => 0;
use constant TWCS_TOP => 1;
use constant TWCS_BOTTOM => 2;
use constant TWDE_CUSTOMEVENTS => 32768;
use constant TWDE_CHECKAUTOMATICCAPTURE => 0;
use constant TWDE_CHECKBATTERY => 1;
use constant TWDE_CHECKDEVICEONLINE => 2;
use constant TWDE_CHECKFLASH => 3;
use constant TWDE_CHECKPOWERSUPPLY => 4;
use constant TWDE_CHECKRESOLUTION => 5;
use constant TWDE_DEVICEADDED => 6;
use constant TWDE_DEVICEOFFLINE => 7;
use constant TWDE_DEVICEREADY => 8;
use constant TWDE_DEVICEREMOVED => 9;
use constant TWDE_IMAGECAPTURED => 10;
use constant TWDE_IMAGEDELETED => 11;
use constant TWDE_PAPERDOUBLEFEED => 12;
use constant TWDE_PAPERJAM => 13;
use constant TWDE_LAMPFAILURE => 14;
use constant TWDE_POWERSAVE => 15;
use constant TWDE_POWERSAVENOTIFY => 16;
use constant TWDR_GET => 1;
use constant TWDR_SET => 2;
use constant TWDSK_SUCCESS => 0;
use constant TWDSK_REPORTONLY => 1;
use constant TWDSK_FAIL => 2;
use constant TWDSK_DISABLED => 3;
use constant TWDX_NONE => 0;
use constant TWDX_1PASSDUPLEX => 1;
use constant TWDX_2PASSDUPLEX => 2;
use constant TWFA_NONE => 0;
use constant TWFA_LEFT => 1;
use constant TWFA_CENTER => 2;
use constant TWFA_RIGHT => 3;
use constant TWFE_GENERAL => 0;
use constant TWFE_PHOTO => 1;
use constant TWFF_TIFF => 0;
use constant TWFF_PICT => 1;
use constant TWFF_BMP => 2;
use constant TWFF_XBM => 3;
use constant TWFF_JFIF => 4;
use constant TWFF_FPX => 5;
use constant TWFF_TIFFMULTI => 6;
use constant TWFF_PNG => 7;
use constant TWFF_SPIFF => 8;
use constant TWFF_EXIF => 9;
use constant TWFF_PDF => 10;
use constant TWFF_JP2 => 11;
use constant TWFF_JPX => 13;
use constant TWFF_DEJAVU => 14;
use constant TWFF_PDFA => 15;
use constant TWFF_PDFA2 => 16;
use constant TWFF_PDFRASTER => 17;
use constant TWFL_NONE => 0;
use constant TWFL_OFF => 1;
use constant TWFL_ON => 2;
use constant TWFL_AUTO => 3;
use constant TWFL_REDEYE => 4;
use constant TWFO_FIRSTPAGEFIRST => 0;
use constant TWFO_LASTPAGEFIRST => 1;
use constant TWFP_POCKETERROR => 0;
use constant TWFP_POCKET1 => 1;
use constant TWFP_POCKET2 => 2;
use constant TWFP_POCKET3 => 3;
use constant TWFP_POCKET4 => 4;
use constant TWFP_POCKET5 => 5;
use constant TWFP_POCKET6 => 6;
use constant TWFP_POCKET7 => 7;
use constant TWFP_POCKET8 => 8;
use constant TWFP_POCKET9 => 9;
use constant TWFP_POCKET10 => 10;
use constant TWFP_POCKET11 => 11;
use constant TWFP_POCKET12 => 12;
use constant TWFP_POCKET13 => 13;
use constant TWFP_POCKET14 => 14;
use constant TWFP_POCKET15 => 15;
use constant TWFP_POCKET16 => 16;
use constant TWFR_BOOK => 0;
use constant TWFR_FANFOLD => 1;
use constant TWFT_RED => 0;
use constant TWFT_GREEN => 1;
use constant TWFT_BLUE => 2;
use constant TWFT_NONE => 3;
use constant TWFT_WHITE => 4;
use constant TWFT_CYAN => 5;
use constant TWFT_MAGENTA => 6;
use constant TWFT_YELLOW => 7;
use constant TWFT_BLACK => 8;
use constant TWFY_CAMERA => 0;
use constant TWFY_CAMERATOP => 1;
use constant TWFY_CAMERABOTTOM => 2;
use constant TWFY_CAMERAPREVIEW => 3;
use constant TWFY_DOMAIN => 4;
use constant TWFY_HOST => 5;
use constant TWFY_DIRECTORY => 6;
use constant TWFY_IMAGE => 7;
use constant TWFY_UNKNOWN => 8;
use constant TWIA_UNUSED => 0;
use constant TWIA_FIXED => 1;
use constant TWIA_LEVEL1 => 2;
use constant TWIA_LEVEL2 => 3;
use constant TWIA_LEVEL3 => 4;
use constant TWIA_LEVEL4 => 5;
use constant TWIC_NONE => 0;
use constant TWIC_LINK => 1;
use constant TWIC_EMBED => 2;
use constant TWIF_NONE => 0;
use constant TWIF_AUTO => 1;
use constant TWIF_LOWPASS => 2;
use constant TWIF_BANDPASS => 3;
use constant TWIF_HIGHPASS => 4;
use constant TWIF_TEXT => 3;
use constant TWIF_FINELINE => 4;
use constant TWIM_NONE => 0;
use constant TWIM_FRONTONTOP => 1;
use constant TWIM_FRONTONBOTTOM => 2;
use constant TWIM_FRONTONLEFT => 3;
use constant TWIM_FRONTONRIGHT => 4;
use constant TWJC_NONE => 0;
use constant TWJC_JSIC => 1;
use constant TWJC_JSIS => 2;
use constant TWJC_JSXC => 3;
use constant TWJC_JSXS => 4;
use constant TWJQ_UNKNOWN => -4;
use constant TWJQ_LOW => -3;
use constant TWJQ_MEDIUM => -2;
use constant TWJQ_HIGH => -1;
use constant TWLP_REFLECTIVE => 0;
use constant TWLP_TRANSMISSIVE => 1;
use constant TWLS_RED => 0;
use constant TWLS_GREEN => 1;
use constant TWLS_BLUE => 2;
use constant TWLS_NONE => 3;
use constant TWLS_WHITE => 4;
use constant TWLS_UV => 5;
use constant TWLS_IR => 6;
use constant TWMD_MICR => 0;
use constant TWMD_RAW => 1;
use constant TWMD_INVALID => 2;
use constant TWNF_NONE => 0;
use constant TWNF_AUTO => 1;
use constant TWNF_LONEPIXEL => 2;
use constant TWNF_MAJORITYRULE => 3;
use constant TWOR_ROT0 => 0;
use constant TWOR_ROT90 => 1;
use constant TWOR_ROT180 => 2;
use constant TWOR_ROT270 => 3;
use constant TWOR_PORTRAIT => 0;
use constant TWOR_LANDSCAPE => 3;
use constant TWOR_AUTO => 4;
use constant TWOR_AUTOTEXT => 5;
use constant TWOR_AUTOPICTURE => 6;
use constant TWOV_NONE => 0;
use constant TWOV_AUTO => 1;
use constant TWOV_TOPBOTTOM => 2;
use constant TWOV_LEFTRIGHT => 3;
use constant TWOV_ALL => 4;
use constant TWPA_RGB => 0;
use constant TWPA_GRAY => 1;
use constant TWPA_CMY => 2;
use constant TWPC_CHUNKY => 0;
use constant TWPC_PLANAR => 1;
use constant TWPCH_PATCH1 => 0;
use constant TWPCH_PATCH2 => 1;
use constant TWPCH_PATCH3 => 2;
use constant TWPCH_PATCH4 => 3;
use constant TWPCH_PATCH6 => 4;
use constant TWPCH_PATCHT => 5;
use constant TWPF_CHOCOLATE => 0;
use constant TWPF_VANILLA => 1;
use constant TWPM_SINGLESTRING => 0;
use constant TWPM_MULTISTRING => 1;
use constant TWPM_COMPOUNDSTRING => 2;
use constant TWPM_IMAGEADDRESSSTRING => 3;
use constant TWPR_IMPRINTERTOPBEFORE => 0;
use constant TWPR_IMPRINTERTOPAFTER => 1;
use constant TWPR_IMPRINTERBOTTOMBEFORE => 2;
use constant TWPR_IMPRINTERBOTTOMAFTER => 3;
use constant TWPR_ENDORSERTOPBEFORE => 4;
use constant TWPR_ENDORSERTOPAFTER => 5;
use constant TWPR_ENDORSERBOTTOMBEFORE => 6;
use constant TWPR_ENDORSERBOTTOMAFTER => 7;
use constant TWPF_NORMAL => 0;
use constant TWPF_BOLD => 1;
use constant TWPF_ITALIC => 2;
use constant TWPF_LARGESIZE => 3;
use constant TWPF_SMALLSIZE => 4;
use constant TWCT_PAGE => 0;
use constant TWCT_PATCH1 => 1;
use constant TWCT_PATCH2 => 2;
use constant TWCT_PATCH3 => 3;
use constant TWCT_PATCH4 => 4;
use constant TWCT_PATCHT => 5;
use constant TWCT_PATCH6 => 6;
use constant TWPS_EXTERNAL => 0;
use constant TWPS_BATTERY => 1;
use constant TWPT_BW => 0;
use constant TWPT_GRAY => 1;
use constant TWPT_RGB => 2;
use constant TWPT_PALETTE => 3;
use constant TWPT_CMY => 4;
use constant TWPT_CMYK => 5;
use constant TWPT_YUV => 6;
use constant TWPT_YUVK => 7;
use constant TWPT_CIEXYZ => 8;
use constant TWPT_LAB => 9;
use constant TWPT_SRGB => 10;
use constant TWPT_SCRGB => 11;
use constant TWPT_INFRARED => 16;
use constant TWSG_NONE => 0;
use constant TWSG_AUTO => 1;
use constant TWSG_MANUAL => 2;
use constant TWFM_POSITIVE => 0;
use constant TWFM_NEGATIVE => 1;
use constant TWDF_ULTRASONIC => 0;
use constant TWDF_BYLENGTH => 1;
use constant TWDF_INFRARED => 2;
use constant TWUS_LOW => 0;
use constant TWUS_MEDIUM => 1;
use constant TWUS_HIGH => 2;
use constant TWDP_STOP => 0;
use constant TWDP_STOPANDWAIT => 1;
use constant TWDP_SOUND => 2;
use constant TWDP_DONOTIMPRINT => 3;
use constant TWMR_NONE => 0;
use constant TWMR_VERTICAL => 1;
use constant TWMR_HORIZONTAL => 2;
use constant TWJS_444YCBCR => 0;
use constant TWJS_444RGB => 1;
use constant TWJS_422 => 2;
use constant TWJS_421 => 3;
use constant TWJS_411 => 4;
use constant TWJS_420 => 5;
use constant TWJS_410 => 6;
use constant TWJS_311 => 7;
use constant TWPH_NORMAL => 0;
use constant TWPH_FRAGILE => 1;
use constant TWPH_THICK => 2;
use constant TWPH_TRIFOLD => 3;
use constant TWPH_PHOTOGRAPH => 4;
use constant TWCI_INFO => 0;
use constant TWCI_WARNING => 1;
use constant TWCI_ERROR => 2;
use constant TWCI_WARMUP => 3;
use constant TWSS_NONE => 0;
use constant TWSS_A4 => 1;
use constant TWSS_JISB5 => 2;
use constant TWSS_USLETTER => 3;
use constant TWSS_USLEGAL => 4;
use constant TWSS_A5 => 5;
use constant TWSS_ISOB4 => 6;
use constant TWSS_ISOB6 => 7;
use constant TWSS_USLEDGER => 9;
use constant TWSS_USEXECUTIVE => 10;
use constant TWSS_A3 => 11;
use constant TWSS_ISOB3 => 12;
use constant TWSS_A6 => 13;
use constant TWSS_C4 => 14;
use constant TWSS_C5 => 15;
use constant TWSS_C6 => 16;
use constant TWSS_4A0 => 17;
use constant TWSS_2A0 => 18;
use constant TWSS_A0 => 19;
use constant TWSS_A1 => 20;
use constant TWSS_A2 => 21;
use constant TWSS_A7 => 22;
use constant TWSS_A8 => 23;
use constant TWSS_A9 => 24;
use constant TWSS_A10 => 25;
use constant TWSS_ISOB0 => 26;
use constant TWSS_ISOB1 => 27;
use constant TWSS_ISOB2 => 28;
use constant TWSS_ISOB5 => 29;
use constant TWSS_ISOB7 => 30;
use constant TWSS_ISOB8 => 31;
use constant TWSS_ISOB9 => 32;
use constant TWSS_ISOB10 => 33;
use constant TWSS_JISB0 => 34;
use constant TWSS_JISB1 => 35;
use constant TWSS_JISB2 => 36;
use constant TWSS_JISB3 => 37;
use constant TWSS_JISB4 => 38;
use constant TWSS_JISB6 => 39;
use constant TWSS_JISB7 => 40;
use constant TWSS_JISB8 => 41;
use constant TWSS_JISB9 => 42;
use constant TWSS_JISB10 => 43;
use constant TWSS_C0 => 44;
use constant TWSS_C1 => 45;
use constant TWSS_C2 => 46;
use constant TWSS_C3 => 47;
use constant TWSS_C7 => 48;
use constant TWSS_C8 => 49;
use constant TWSS_C9 => 50;
use constant TWSS_C10 => 51;
use constant TWSS_USSTATEMENT => 52;
use constant TWSS_BUSINESSCARD => 53;
use constant TWSS_MAXSIZE => 54;
use constant TWSX_NATIVE => 0;
use constant TWSX_FILE => 1;
use constant TWSX_MEMORY => 2;
use constant TWSX_MEMFILE => 4;
use constant TWUN_INCHES => 0;
use constant TWUN_CENTIMETERS => 1;
use constant TWUN_PICAS => 2;
use constant TWUN_POINTS => 3;
use constant TWUN_TWIPS => 4;
use constant TWUN_PIXELS => 5;
use constant TWUN_MILLIMETERS => 6;
use constant TWCY_AFGHANISTAN => 1001;
use constant TWCY_ALGERIA => 213;
use constant TWCY_AMERICANSAMOA => 684;
use constant TWCY_ANDORRA => 33;
use constant TWCY_ANGOLA => 1002;
use constant TWCY_ANGUILLA => 8090;
use constant TWCY_ANTIGUA => 8091;
use constant TWCY_ARGENTINA => 54;
use constant TWCY_ARUBA => 297;
use constant TWCY_ASCENSIONI => 247;
use constant TWCY_AUSTRALIA => 61;
use constant TWCY_AUSTRIA => 43;
use constant TWCY_BAHAMAS => 8092;
use constant TWCY_BAHRAIN => 973;
use constant TWCY_BANGLADESH => 880;
use constant TWCY_BARBADOS => 8093;
use constant TWCY_BELGIUM => 32;
use constant TWCY_BELIZE => 501;
use constant TWCY_BENIN => 229;
use constant TWCY_BERMUDA => 8094;
use constant TWCY_BHUTAN => 1003;
use constant TWCY_BOLIVIA => 591;
use constant TWCY_BOTSWANA => 267;
use constant TWCY_BRITAIN => 6;
use constant TWCY_BRITVIRGINIS => 8095;
use constant TWCY_BRAZIL => 55;
use constant TWCY_BRUNEI => 673;
use constant TWCY_BULGARIA => 359;
use constant TWCY_BURKINAFASO => 1004;
use constant TWCY_BURMA => 1005;
use constant TWCY_BURUNDI => 1006;
use constant TWCY_CAMAROON => 237;
use constant TWCY_CANADA => 2;
use constant TWCY_CAPEVERDEIS => 238;
use constant TWCY_CAYMANIS => 8096;
use constant TWCY_CENTRALAFREP => 1007;
use constant TWCY_CHAD => 1008;
use constant TWCY_CHILE => 56;
use constant TWCY_CHINA => 86;
use constant TWCY_CHRISTMASIS => 1009;
use constant TWCY_COCOSIS => 1009;
use constant TWCY_COLOMBIA => 57;
use constant TWCY_COMOROS => 1010;
use constant TWCY_CONGO => 1011;
use constant TWCY_COOKIS => 1012;
use constant TWCY_COSTARICA => 506;
use constant TWCY_CUBA => 5;
use constant TWCY_CYPRUS => 357;
use constant TWCY_CZECHOSLOVAKIA => 42;
use constant TWCY_DENMARK => 45;
use constant TWCY_DJIBOUTI => 1013;
use constant TWCY_DOMINICA => 8097;
use constant TWCY_DOMINCANREP => 8098;
use constant TWCY_EASTERIS => 1014;
use constant TWCY_ECUADOR => 593;
use constant TWCY_EGYPT => 20;
use constant TWCY_ELSALVADOR => 503;
use constant TWCY_EQGUINEA => 1015;
use constant TWCY_ETHIOPIA => 251;
use constant TWCY_FALKLANDIS => 1016;
use constant TWCY_FAEROEIS => 298;
use constant TWCY_FIJIISLANDS => 679;
use constant TWCY_FINLAND => 358;
use constant TWCY_FRANCE => 33;
use constant TWCY_FRANTILLES => 596;
use constant TWCY_FRGUIANA => 594;
use constant TWCY_FRPOLYNEISA => 689;
use constant TWCY_FUTANAIS => 1043;
use constant TWCY_GABON => 241;
use constant TWCY_GAMBIA => 220;
use constant TWCY_GERMANY => 49;
use constant TWCY_GHANA => 233;
use constant TWCY_GIBRALTER => 350;
use constant TWCY_GREECE => 30;
use constant TWCY_GREENLAND => 299;
use constant TWCY_GRENADA => 8099;
use constant TWCY_GRENEDINES => 8015;
use constant TWCY_GUADELOUPE => 590;
use constant TWCY_GUAM => 671;
use constant TWCY_GUANTANAMOBAY => 5399;
use constant TWCY_GUATEMALA => 502;
use constant TWCY_GUINEA => 224;
use constant TWCY_GUINEABISSAU => 1017;
use constant TWCY_GUYANA => 592;
use constant TWCY_HAITI => 509;
use constant TWCY_HONDURAS => 504;
use constant TWCY_HONGKONG => 852;
use constant TWCY_HUNGARY => 36;
use constant TWCY_ICELAND => 354;
use constant TWCY_INDIA => 91;
use constant TWCY_INDONESIA => 62;
use constant TWCY_IRAN => 98;
use constant TWCY_IRAQ => 964;
use constant TWCY_IRELAND => 353;
use constant TWCY_ISRAEL => 972;
use constant TWCY_ITALY => 39;
use constant TWCY_IVORYCOAST => 225;
use constant TWCY_JAMAICA => 8010;
use constant TWCY_JAPAN => 81;
use constant TWCY_JORDAN => 962;
use constant TWCY_KENYA => 254;
use constant TWCY_KIRIBATI => 1018;
use constant TWCY_KOREA => 82;
use constant TWCY_KUWAIT => 965;
use constant TWCY_LAOS => 1019;
use constant TWCY_LEBANON => 1020;
use constant TWCY_LIBERIA => 231;
use constant TWCY_LIBYA => 218;
use constant TWCY_LIECHTENSTEIN => 41;
use constant TWCY_LUXENBOURG => 352;
use constant TWCY_MACAO => 853;
use constant TWCY_MADAGASCAR => 1021;
use constant TWCY_MALAWI => 265;
use constant TWCY_MALAYSIA => 60;
use constant TWCY_MALDIVES => 960;
use constant TWCY_MALI => 1022;
use constant TWCY_MALTA => 356;
use constant TWCY_MARSHALLIS => 692;
use constant TWCY_MAURITANIA => 1023;
use constant TWCY_MAURITIUS => 230;
use constant TWCY_MEXICO => 3;
use constant TWCY_MICRONESIA => 691;
use constant TWCY_MIQUELON => 508;
use constant TWCY_MONACO => 33;
use constant TWCY_MONGOLIA => 1024;
use constant TWCY_MONTSERRAT => 8011;
use constant TWCY_MOROCCO => 212;
use constant TWCY_MOZAMBIQUE => 1025;
use constant TWCY_NAMIBIA => 264;
use constant TWCY_NAURU => 1026;
use constant TWCY_NEPAL => 977;
use constant TWCY_NETHERLANDS => 31;
use constant TWCY_NETHANTILLES => 599;
use constant TWCY_NEVIS => 8012;
use constant TWCY_NEWCALEDONIA => 687;
use constant TWCY_NEWZEALAND => 64;
use constant TWCY_NICARAGUA => 505;
use constant TWCY_NIGER => 227;
use constant TWCY_NIGERIA => 234;
use constant TWCY_NIUE => 1027;
use constant TWCY_NORFOLKI => 1028;
use constant TWCY_NORWAY => 47;
use constant TWCY_OMAN => 968;
use constant TWCY_PAKISTAN => 92;
use constant TWCY_PALAU => 1029;
use constant TWCY_PANAMA => 507;
use constant TWCY_PARAGUAY => 595;
use constant TWCY_PERU => 51;
use constant TWCY_PHILLIPPINES => 63;
use constant TWCY_PITCAIRNIS => 1030;
use constant TWCY_PNEWGUINEA => 675;
use constant TWCY_POLAND => 48;
use constant TWCY_PORTUGAL => 351;
use constant TWCY_QATAR => 974;
use constant TWCY_REUNIONI => 1031;
use constant TWCY_ROMANIA => 40;
use constant TWCY_RWANDA => 250;
use constant TWCY_SAIPAN => 670;
use constant TWCY_SANMARINO => 39;
use constant TWCY_SAOTOME => 1033;
use constant TWCY_SAUDIARABIA => 966;
use constant TWCY_SENEGAL => 221;
use constant TWCY_SEYCHELLESIS => 1034;
use constant TWCY_SIERRALEONE => 1035;
use constant TWCY_SINGAPORE => 65;
use constant TWCY_SOLOMONIS => 1036;
use constant TWCY_SOMALI => 1037;
use constant TWCY_SOUTHAFRICA => 27;
use constant TWCY_SPAIN => 34;
use constant TWCY_SRILANKA => 94;
use constant TWCY_STHELENA => 1032;
use constant TWCY_STKITTS => 8013;
use constant TWCY_STLUCIA => 8014;
use constant TWCY_STPIERRE => 508;
use constant TWCY_STVINCENT => 8015;
use constant TWCY_SUDAN => 1038;
use constant TWCY_SURINAME => 597;
use constant TWCY_SWAZILAND => 268;
use constant TWCY_SWEDEN => 46;
use constant TWCY_SWITZERLAND => 41;
use constant TWCY_SYRIA => 1039;
use constant TWCY_TAIWAN => 886;
use constant TWCY_TANZANIA => 255;
use constant TWCY_THAILAND => 66;
use constant TWCY_TOBAGO => 8016;
use constant TWCY_TOGO => 228;
use constant TWCY_TONGAIS => 676;
use constant TWCY_TRINIDAD => 8016;
use constant TWCY_TUNISIA => 216;
use constant TWCY_TURKEY => 90;
use constant TWCY_TURKSCAICOS => 8017;
use constant TWCY_TUVALU => 1040;
use constant TWCY_UGANDA => 256;
use constant TWCY_USSR => 7;
use constant TWCY_UAEMIRATES => 971;
use constant TWCY_UNITEDKINGDOM => 44;
use constant TWCY_USA => 1;
use constant TWCY_URUGUAY => 598;
use constant TWCY_VANUATU => 1041;
use constant TWCY_VATICANCITY => 39;
use constant TWCY_VENEZUELA => 58;
use constant TWCY_WAKE => 1042;
use constant TWCY_WALLISIS => 1043;
use constant TWCY_WESTERNSAHARA => 1044;
use constant TWCY_WESTERNSAMOA => 1045;
use constant TWCY_YEMEN => 1046;
use constant TWCY_YUGOSLAVIA => 38;
use constant TWCY_ZAIRE => 243;
use constant TWCY_ZAMBIA => 260;
use constant TWCY_ZIMBABWE => 263;
use constant TWCY_ALBANIA => 355;
use constant TWCY_ARMENIA => 374;
use constant TWCY_AZERBAIJAN => 994;
use constant TWCY_BELARUS => 375;
use constant TWCY_BOSNIAHERZGO => 387;
use constant TWCY_CAMBODIA => 855;
use constant TWCY_CROATIA => 385;
use constant TWCY_CZECHREPUBLIC => 420;
use constant TWCY_DIEGOGARCIA => 246;
use constant TWCY_ERITREA => 291;
use constant TWCY_ESTONIA => 372;
use constant TWCY_GEORGIA => 995;
use constant TWCY_LATVIA => 371;
use constant TWCY_LESOTHO => 266;
use constant TWCY_LITHUANIA => 370;
use constant TWCY_MACEDONIA => 389;
use constant TWCY_MAYOTTEIS => 269;
use constant TWCY_MOLDOVA => 373;
use constant TWCY_MYANMAR => 95;
use constant TWCY_NORTHKOREA => 850;
use constant TWCY_PUERTORICO => 787;
use constant TWCY_RUSSIA => 7;
use constant TWCY_SERBIA => 381;
use constant TWCY_SLOVAKIA => 421;
use constant TWCY_SLOVENIA => 386;
use constant TWCY_SOUTHKOREA => 82;
use constant TWCY_UKRAINE => 380;
use constant TWCY_USVIRGINIS => 340;
use constant TWCY_VIETNAM => 84;
use constant TWLG_USERLOCALE => -1;
use constant TWLG_DAN => 0;
use constant TWLG_DUT => 1;
use constant TWLG_ENG => 2;
use constant TWLG_FCF => 3;
use constant TWLG_FIN => 4;
use constant TWLG_FRN => 5;
use constant TWLG_GER => 6;
use constant TWLG_ICE => 7;
use constant TWLG_ITN => 8;
use constant TWLG_NOR => 9;
use constant TWLG_POR => 10;
use constant TWLG_SPA => 11;
use constant TWLG_SWE => 12;
use constant TWLG_USA => 13;
use constant TWLG_AFRIKAANS => 14;
use constant TWLG_ALBANIA => 15;
use constant TWLG_ARABIC => 16;
use constant TWLG_ARABIC_ALGERIA => 17;
use constant TWLG_ARABIC_BAHRAIN => 18;
use constant TWLG_ARABIC_EGYPT => 19;
use constant TWLG_ARABIC_IRAQ => 20;
use constant TWLG_ARABIC_JORDAN => 21;
use constant TWLG_ARABIC_KUWAIT => 22;
use constant TWLG_ARABIC_LEBANON => 23;
use constant TWLG_ARABIC_LIBYA => 24;
use constant TWLG_ARABIC_MOROCCO => 25;
use constant TWLG_ARABIC_OMAN => 26;
use constant TWLG_ARABIC_QATAR => 27;
use constant TWLG_ARABIC_SAUDIARABIA => 28;
use constant TWLG_ARABIC_SYRIA => 29;
use constant TWLG_ARABIC_TUNISIA => 30;
use constant TWLG_ARABIC_UAE => 31;
use constant TWLG_ARABIC_YEMEN => 32;
use constant TWLG_BASQUE => 33;
use constant TWLG_BYELORUSSIAN => 34;
use constant TWLG_BULGARIAN => 35;
use constant TWLG_CATALAN => 36;
use constant TWLG_CHINESE => 37;
use constant TWLG_CHINESE_HONGKONG => 38;
use constant TWLG_CHINESE_PRC => 39;
use constant TWLG_CHINESE_SINGAPORE => 40;
use constant TWLG_CHINESE_SIMPLIFIED => 41;
use constant TWLG_CHINESE_TAIWAN => 42;
use constant TWLG_CHINESE_TRADITIONAL => 43;
use constant TWLG_CROATIA => 44;
use constant TWLG_CZECH => 45;
use constant TWLG_DANISH => 0;
use constant TWLG_DUTCH => 1;
use constant TWLG_DUTCH_BELGIAN => 46;
use constant TWLG_ENGLISH => 2;
use constant TWLG_ENGLISH_AUSTRALIAN => 47;
use constant TWLG_ENGLISH_CANADIAN => 48;
use constant TWLG_ENGLISH_IRELAND => 49;
use constant TWLG_ENGLISH_NEWZEALAND => 50;
use constant TWLG_ENGLISH_SOUTHAFRICA => 51;
use constant TWLG_ENGLISH_UK => 52;
use constant TWLG_ENGLISH_USA => 13;
use constant TWLG_ESTONIAN => 53;
use constant TWLG_FAEROESE => 54;
use constant TWLG_FARSI => 55;
use constant TWLG_FINNISH => 4;
use constant TWLG_FRENCH => 5;
use constant TWLG_FRENCH_BELGIAN => 56;
use constant TWLG_FRENCH_CANADIAN => 3;
use constant TWLG_FRENCH_LUXEMBOURG => 57;
use constant TWLG_FRENCH_SWISS => 58;
use constant TWLG_GERMAN => 6;
use constant TWLG_GERMAN_AUSTRIAN => 59;
use constant TWLG_GERMAN_LUXEMBOURG => 60;
use constant TWLG_GERMAN_LIECHTENSTEIN => 61;
use constant TWLG_GERMAN_SWISS => 62;
use constant TWLG_GREEK => 63;
use constant TWLG_HEBREW => 64;
use constant TWLG_HUNGARIAN => 65;
use constant TWLG_ICELANDIC => 7;
use constant TWLG_INDONESIAN => 66;
use constant TWLG_ITALIAN => 8;
use constant TWLG_ITALIAN_SWISS => 67;
use constant TWLG_JAPANESE => 68;
use constant TWLG_KOREAN => 69;
use constant TWLG_KOREAN_JOHAB => 70;
use constant TWLG_LATVIAN => 71;
use constant TWLG_LITHUANIAN => 72;
use constant TWLG_NORWEGIAN => 9;
use constant TWLG_NORWEGIAN_BOKMAL => 73;
use constant TWLG_NORWEGIAN_NYNORSK => 74;
use constant TWLG_POLISH => 75;
use constant TWLG_PORTUGUESE => 10;
use constant TWLG_PORTUGUESE_BRAZIL => 76;
use constant TWLG_ROMANIAN => 77;
use constant TWLG_RUSSIAN => 78;
use constant TWLG_SERBIAN_LATIN => 79;
use constant TWLG_SLOVAK => 80;
use constant TWLG_SLOVENIAN => 81;
use constant TWLG_SPANISH => 11;
use constant TWLG_SPANISH_MEXICAN => 82;
use constant TWLG_SPANISH_MODERN => 83;
use constant TWLG_SWEDISH => 12;
use constant TWLG_THAI => 84;
use constant TWLG_TURKISH => 85;
use constant TWLG_UKRANIAN => 86;
use constant TWLG_ASSAMESE => 87;
use constant TWLG_BENGALI => 88;
use constant TWLG_BIHARI => 89;
use constant TWLG_BODO => 90;
use constant TWLG_DOGRI => 91;
use constant TWLG_GUJARATI => 92;
use constant TWLG_HARYANVI => 93;
use constant TWLG_HINDI => 94;
use constant TWLG_KANNADA => 95;
use constant TWLG_KASHMIRI => 96;
use constant TWLG_MALAYALAM => 97;
use constant TWLG_MARATHI => 98;
use constant TWLG_MARWARI => 99;
use constant TWLG_MEGHALAYAN => 100;
use constant TWLG_MIZO => 101;
use constant TWLG_NAGA => 102;
use constant TWLG_ORISSI => 103;
use constant TWLG_PUNJABI => 104;
use constant TWLG_PUSHTU => 105;
use constant TWLG_SERBIAN_CYRILLIC => 106;
use constant TWLG_SIKKIMI => 107;
use constant TWLG_SWEDISH_FINLAND => 108;
use constant TWLG_TAMIL => 109;
use constant TWLG_TELUGU => 110;
use constant TWLG_TRIPURI => 111;
use constant TWLG_URDU => 112;
use constant TWLG_VIETNAMESE => 113;
use constant DG_CONTROL => 1;
use constant DG_IMAGE => 2;
use constant DG_AUDIO => 4;
use constant DF_DSM2 => 268435456;
use constant DF_APP2 => 536870912;
use constant DF_DS2 => 1073741824;
use constant DG_MASK => 65535;
use constant DAT_NULL => 0;
use constant DAT_CUSTOMBASE => 32768;
use constant DAT_CAPABILITY => 1;
use constant DAT_EVENT => 2;
use constant DAT_IDENTITY => 3;
use constant DAT_PARENT => 4;
use constant DAT_PENDINGXFERS => 5;
use constant DAT_SETUPMEMXFER => 6;
use constant DAT_SETUPFILEXFER => 7;
use constant DAT_STATUS => 8;
use constant DAT_USERINTERFACE => 9;
use constant DAT_XFERGROUP => 10;
use constant DAT_CUSTOMDSDATA => 12;
use constant DAT_DEVICEEVENT => 13;
use constant DAT_FILESYSTEM => 14;
use constant DAT_PASSTHRU => 15;
use constant DAT_CALLBACK => 16;
use constant DAT_STATUSUTF8 => 17;
use constant DAT_CALLBACK2 => 18;
use constant DAT_METRICS => 19;
use constant DAT_TWAINDIRECT => 20;
use constant DAT_IMAGEINFO => 257;
use constant DAT_IMAGELAYOUT => 258;
use constant DAT_IMAGEMEMXFER => 259;
use constant DAT_IMAGENATIVEXFER => 260;
use constant DAT_IMAGEFILEXFER => 261;
use constant DAT_CIECOLOR => 262;
use constant DAT_GRAYRESPONSE => 263;
use constant DAT_RGBRESPONSE => 264;
use constant DAT_JPEGCOMPRESSION => 265;
use constant DAT_PALETTE8 => 266;
use constant DAT_EXTIMAGEINFO => 267;
use constant DAT_FILTER => 268;
use constant DAT_AUDIOFILEXFER => 513;
use constant DAT_AUDIOINFO => 514;
use constant DAT_AUDIONATIVEXFER => 515;
use constant DAT_ICCPROFILE => 1025;
use constant DAT_IMAGEMEMFILEXFER => 1026;
use constant DAT_ENTRYPOINT => 1027;
use constant MSG_NULL => 0;
use constant MSG_CUSTOMBASE => 32768;
use constant MSG_GET => 1;
use constant MSG_GETCURRENT => 2;
use constant MSG_GETDEFAULT => 3;
use constant MSG_GETFIRST => 4;
use constant MSG_GETNEXT => 5;
use constant MSG_SET => 6;
use constant MSG_RESET => 7;
use constant MSG_QUERYSUPPORT => 8;
use constant MSG_GETHELP => 9;
use constant MSG_GETLABEL => 10;
use constant MSG_GETLABELENUM => 11;
use constant MSG_SETCONSTRAINT => 12;
use constant MSG_XFERREADY => 257;
use constant MSG_CLOSEDSREQ => 258;
use constant MSG_CLOSEDSOK => 259;
use constant MSG_DEVICEEVENT => 260;
use constant MSG_OPENDSM => 769;
use constant MSG_CLOSEDSM => 770;
use constant MSG_OPENDS => 1025;
use constant MSG_CLOSEDS => 1026;
use constant MSG_USERSELECT => 1027;
use constant MSG_DISABLEDS => 1281;
use constant MSG_ENABLEDS => 1282;
use constant MSG_ENABLEDSUIONLY => 1283;
use constant MSG_PROCESSEVENT => 1537;
use constant MSG_ENDXFER => 1793;
use constant MSG_STOPFEEDER => 1794;
use constant MSG_CHANGEDIRECTORY => 2049;
use constant MSG_CREATEDIRECTORY => 2050;
use constant MSG_DELETE => 2051;
use constant MSG_FORMATMEDIA => 2052;
use constant MSG_GETCLOSE => 2053;
use constant MSG_GETFIRSTFILE => 2054;
use constant MSG_GETINFO => 2055;
use constant MSG_GETNEXTFILE => 2056;
use constant MSG_RENAME => 2057;
use constant MSG_COPY => 2058;
use constant MSG_AUTOMATICCAPTUREDIRECTORY => 2059;
use constant MSG_PASSTHRU => 2305;
use constant MSG_REGISTER_CALLBACK => 2306;
use constant MSG_RESETALL => 2561;
use constant MSG_SETTASK => 2817;
use constant CAP_CUSTOMBASE => 32768;
use constant CAP_XFERCOUNT => 1;
use constant ICAP_COMPRESSION => 256;
use constant ICAP_PIXELTYPE => 257;
use constant ICAP_UNITS => 258;
use constant ICAP_XFERMECH => 259;
use constant CAP_AUTHOR => 4096;
use constant CAP_CAPTION => 4097;
use constant CAP_FEEDERENABLED => 4098;
use constant CAP_FEEDERLOADED => 4099;
use constant CAP_TIMEDATE => 4100;
use constant CAP_SUPPORTEDCAPS => 4101;
use constant CAP_EXTENDEDCAPS => 4102;
use constant CAP_AUTOFEED => 4103;
use constant CAP_CLEARPAGE => 4104;
use constant CAP_FEEDPAGE => 4105;
use constant CAP_REWINDPAGE => 4106;
use constant CAP_INDICATORS => 4107;
use constant CAP_PAPERDETECTABLE => 4109;
use constant CAP_UICONTROLLABLE => 4110;
use constant CAP_DEVICEONLINE => 4111;
use constant CAP_AUTOSCAN => 4112;
use constant CAP_THUMBNAILSENABLED => 4113;
use constant CAP_DUPLEX => 4114;
use constant CAP_DUPLEXENABLED => 4115;
use constant CAP_ENABLEDSUIONLY => 4116;
use constant CAP_CUSTOMDSDATA => 4117;
use constant CAP_ENDORSER => 4118;
use constant CAP_JOBCONTROL => 4119;
use constant CAP_ALARMS => 4120;
use constant CAP_ALARMVOLUME => 4121;
use constant CAP_AUTOMATICCAPTURE => 4122;
use constant CAP_TIMEBEFOREFIRSTCAPTURE => 4123;
use constant CAP_TIMEBETWEENCAPTURES => 4124;
use constant CAP_MAXBATCHBUFFERS => 4126;
use constant CAP_DEVICETIMEDATE => 4127;
use constant CAP_POWERSUPPLY => 4128;
use constant CAP_CAMERAPREVIEWUI => 4129;
use constant CAP_DEVICEEVENT => 4130;
use constant CAP_SERIALNUMBER => 4132;
use constant CAP_PRINTER => 4134;
use constant CAP_PRINTERENABLED => 4135;
use constant CAP_PRINTERINDEX => 4136;
use constant CAP_PRINTERMODE => 4137;
use constant CAP_PRINTERSTRING => 4138;
use constant CAP_PRINTERSUFFIX => 4139;
use constant CAP_LANGUAGE => 4140;
use constant CAP_FEEDERALIGNMENT => 4141;
use constant CAP_FEEDERORDER => 4142;
use constant CAP_REACQUIREALLOWED => 4144;
use constant CAP_BATTERYMINUTES => 4146;
use constant CAP_BATTERYPERCENTAGE => 4147;
use constant CAP_CAMERASIDE => 4148;
use constant CAP_SEGMENTED => 4149;
use constant CAP_CAMERAENABLED => 4150;
use constant CAP_CAMERAORDER => 4151;
use constant CAP_MICRENABLED => 4152;
use constant CAP_FEEDERPREP => 4153;
use constant CAP_FEEDERPOCKET => 4154;
use constant CAP_AUTOMATICSENSEMEDIUM => 4155;
use constant CAP_CUSTOMINTERFACEGUID => 4156;
use constant CAP_SUPPORTEDCAPSSEGMENTUNIQUE => 4157;
use constant CAP_SUPPORTEDDATS => 4158;
use constant CAP_DOUBLEFEEDDETECTION => 4159;
use constant CAP_DOUBLEFEEDDETECTIONLENGTH => 4160;
use constant CAP_DOUBLEFEEDDETECTIONSENSITIVITY => 4161;
use constant CAP_DOUBLEFEEDDETECTIONRESPONSE => 4162;
use constant CAP_PAPERHANDLING => 4163;
use constant CAP_INDICATORSMODE => 4164;
use constant CAP_PRINTERVERTICALOFFSET => 4165;
use constant CAP_POWERSAVETIME => 4166;
use constant CAP_PRINTERCHARROTATION => 4167;
use constant CAP_PRINTERFONTSTYLE => 4168;
use constant CAP_PRINTERINDEXLEADCHAR => 4169;
use constant CAP_PRINTERINDEXMAXVALUE => 4170;
use constant CAP_PRINTERINDEXNUMDIGITS => 4171;
use constant CAP_PRINTERINDEXSTEP => 4172;
use constant CAP_PRINTERINDEXTRIGGER => 4173;
use constant CAP_PRINTERSTRINGPREVIEW => 4174;
use constant CAP_SHEETCOUNT => 4175;
use constant CAP_IMAGEADDRESSENABLED => 4176;
use constant CAP_IAFIELDA_LEVEL => 4177;
use constant CAP_IAFIELDB_LEVEL => 4178;
use constant CAP_IAFIELDC_LEVEL => 4179;
use constant CAP_IAFIELDD_LEVEL => 4180;
use constant CAP_IAFIELDE_LEVEL => 4181;
use constant CAP_IAFIELDA_PRINTFORMAT => 4182;
use constant CAP_IAFIELDB_PRINTFORMAT => 4183;
use constant CAP_IAFIELDC_PRINTFORMAT => 4184;
use constant CAP_IAFIELDD_PRINTFORMAT => 4185;
use constant CAP_IAFIELDE_PRINTFORMAT => 4186;
use constant CAP_IAFIELDA_VALUE => 4187;
use constant CAP_IAFIELDB_VALUE => 4188;
use constant CAP_IAFIELDC_VALUE => 4189;
use constant CAP_IAFIELDD_VALUE => 4190;
use constant CAP_IAFIELDE_VALUE => 4191;
use constant CAP_IAFIELDA_LASTPAGE => 4192;
use constant CAP_IAFIELDB_LASTPAGE => 4193;
use constant CAP_IAFIELDC_LASTPAGE => 4194;
use constant CAP_IAFIELDD_LASTPAGE => 4195;
use constant CAP_IAFIELDE_LASTPAGE => 4196;
use constant ICAP_AUTOBRIGHT => 4352;
use constant ICAP_BRIGHTNESS => 4353;
use constant ICAP_CONTRAST => 4355;
use constant ICAP_CUSTHALFTONE => 4356;
use constant ICAP_EXPOSURETIME => 4357;
use constant ICAP_FILTER => 4358;
use constant ICAP_FLASHUSED => 4359;
use constant ICAP_GAMMA => 4360;
use constant ICAP_HALFTONES => 4361;
use constant ICAP_HIGHLIGHT => 4362;
use constant ICAP_IMAGEFILEFORMAT => 4364;
use constant ICAP_LAMPSTATE => 4365;
use constant ICAP_LIGHTSOURCE => 4366;
use constant ICAP_ORIENTATION => 4368;
use constant ICAP_PHYSICALWIDTH => 4369;
use constant ICAP_PHYSICALHEIGHT => 4370;
use constant ICAP_SHADOW => 4371;
use constant ICAP_FRAMES => 4372;
use constant ICAP_XNATIVERESOLUTION => 4374;
use constant ICAP_YNATIVERESOLUTION => 4375;
use constant ICAP_XRESOLUTION => 4376;
use constant ICAP_YRESOLUTION => 4377;
use constant ICAP_MAXFRAMES => 4378;
use constant ICAP_TILES => 4379;
use constant ICAP_BITORDER => 4380;
use constant ICAP_CCITTKFACTOR => 4381;
use constant ICAP_LIGHTPATH => 4382;
use constant ICAP_PIXELFLAVOR => 4383;
use constant ICAP_PLANARCHUNKY => 4384;
use constant ICAP_ROTATION => 4385;
use constant ICAP_SUPPORTEDSIZES => 4386;
use constant ICAP_THRESHOLD => 4387;
use constant ICAP_XSCALING => 4388;
use constant ICAP_YSCALING => 4389;
use constant ICAP_BITORDERCODES => 4390;
use constant ICAP_PIXELFLAVORCODES => 4391;
use constant ICAP_JPEGPIXELTYPE => 4392;
use constant ICAP_TIMEFILL => 4394;
use constant ICAP_BITDEPTH => 4395;
use constant ICAP_BITDEPTHREDUCTION => 4396;
use constant ICAP_UNDEFINEDIMAGESIZE => 4397;
use constant ICAP_IMAGEDATASET => 4398;
use constant ICAP_EXTIMAGEINFO => 4399;
use constant ICAP_MINIMUMHEIGHT => 4400;
use constant ICAP_MINIMUMWIDTH => 4401;
use constant ICAP_AUTODISCARDBLANKPAGES => 4404;
use constant ICAP_FLIPROTATION => 4406;
use constant ICAP_BARCODEDETECTIONENABLED => 4407;
use constant ICAP_SUPPORTEDBARCODETYPES => 4408;
use constant ICAP_BARCODEMAXSEARCHPRIORITIES => 4409;
use constant ICAP_BARCODESEARCHPRIORITIES => 4410;
use constant ICAP_BARCODESEARCHMODE => 4411;
use constant ICAP_BARCODEMAXRETRIES => 4412;
use constant ICAP_BARCODETIMEOUT => 4413;
use constant ICAP_ZOOMFACTOR => 4414;
use constant ICAP_PATCHCODEDETECTIONENABLED => 4415;
use constant ICAP_SUPPORTEDPATCHCODETYPES => 4416;
use constant ICAP_PATCHCODEMAXSEARCHPRIORITIES => 4417;
use constant ICAP_PATCHCODESEARCHPRIORITIES => 4418;
use constant ICAP_PATCHCODESEARCHMODE => 4419;
use constant ICAP_PATCHCODEMAXRETRIES => 4420;
use constant ICAP_PATCHCODETIMEOUT => 4421;
use constant ICAP_FLASHUSED2 => 4422;
use constant ICAP_IMAGEFILTER => 4423;
use constant ICAP_NOISEFILTER => 4424;
use constant ICAP_OVERSCAN => 4425;
use constant ICAP_AUTOMATICBORDERDETECTION => 4432;
use constant ICAP_AUTOMATICDESKEW => 4433;
use constant ICAP_AUTOMATICROTATE => 4434;
use constant ICAP_JPEGQUALITY => 4435;
use constant ICAP_FEEDERTYPE => 4436;
use constant ICAP_ICCPROFILE => 4437;
use constant ICAP_AUTOSIZE => 4438;
use constant ICAP_AUTOMATICCROPUSESFRAME => 4439;
use constant ICAP_AUTOMATICLENGTHDETECTION => 4440;
use constant ICAP_AUTOMATICCOLORENABLED => 4441;
use constant ICAP_AUTOMATICCOLORNONCOLORPIXELTYPE => 4442;
use constant ICAP_COLORMANAGEMENTENABLED => 4443;
use constant ICAP_IMAGEMERGE => 4444;
use constant ICAP_IMAGEMERGEHEIGHTTHRESHOLD => 4445;
use constant ICAP_SUPPORTEDEXTIMAGEINFO => 4446;
use constant ICAP_FILMTYPE => 4447;
use constant ICAP_MIRROR => 4448;
use constant ICAP_JPEGSUBSAMPLING => 4449;
use constant ACAP_XFERMECH => 4610;
use constant TWEI_BARCODEX => 4608;
use constant TWEI_BARCODEY => 4609;
use constant TWEI_BARCODETEXT => 4610;
use constant TWEI_BARCODETYPE => 4611;
use constant TWEI_DESHADETOP => 4612;
use constant TWEI_DESHADELEFT => 4613;
use constant TWEI_DESHADEHEIGHT => 4614;
use constant TWEI_DESHADEWIDTH => 4615;
use constant TWEI_DESHADESIZE => 4616;
use constant TWEI_SPECKLESREMOVED => 4617;
use constant TWEI_HORZLINEXCOORD => 4618;
use constant TWEI_HORZLINEYCOORD => 4619;
use constant TWEI_HORZLINELENGTH => 4620;
use constant TWEI_HORZLINETHICKNESS => 4621;
use constant TWEI_VERTLINEXCOORD => 4622;
use constant TWEI_VERTLINEYCOORD => 4623;
use constant TWEI_VERTLINELENGTH => 4624;
use constant TWEI_VERTLINETHICKNESS => 4625;
use constant TWEI_PATCHCODE => 4626;
use constant TWEI_ENDORSEDTEXT => 4627;
use constant TWEI_FORMCONFIDENCE => 4628;
use constant TWEI_FORMTEMPLATEMATCH => 4629;
use constant TWEI_FORMTEMPLATEPAGEMATCH => 4630;
use constant TWEI_FORMHORZDOCOFFSET => 4631;
use constant TWEI_FORMVERTDOCOFFSET => 4632;
use constant TWEI_BARCODECOUNT => 4633;
use constant TWEI_BARCODECONFIDENCE => 4634;
use constant TWEI_BARCODEROTATION => 4635;
use constant TWEI_BARCODETEXTLENGTH => 4636;
use constant TWEI_DESHADECOUNT => 4637;
use constant TWEI_DESHADEBLACKCOUNTOLD => 4638;
use constant TWEI_DESHADEBLACKCOUNTNEW => 4639;
use constant TWEI_DESHADEBLACKRLMIN => 4640;
use constant TWEI_DESHADEBLACKRLMAX => 4641;
use constant TWEI_DESHADEWHITECOUNTOLD => 4642;
use constant TWEI_DESHADEWHITECOUNTNEW => 4643;
use constant TWEI_DESHADEWHITERLMIN => 4644;
use constant TWEI_DESHADEWHITERLAVE => 4645;
use constant TWEI_DESHADEWHITERLMAX => 4646;
use constant TWEI_BLACKSPECKLESREMOVED => 4647;
use constant TWEI_WHITESPECKLESREMOVED => 4648;
use constant TWEI_HORZLINECOUNT => 4649;
use constant TWEI_VERTLINECOUNT => 4650;
use constant TWEI_DESKEWSTATUS => 4651;
use constant TWEI_SKEWORIGINALANGLE => 4652;
use constant TWEI_SKEWFINALANGLE => 4653;
use constant TWEI_SKEWCONFIDENCE => 4654;
use constant TWEI_SKEWWINDOWX1 => 4655;
use constant TWEI_SKEWWINDOWY1 => 4656;
use constant TWEI_SKEWWINDOWX2 => 4657;
use constant TWEI_SKEWWINDOWY2 => 4658;
use constant TWEI_SKEWWINDOWX3 => 4659;
use constant TWEI_SKEWWINDOWY3 => 4660;
use constant TWEI_SKEWWINDOWX4 => 4661;
use constant TWEI_SKEWWINDOWY4 => 4662;
use constant TWEI_BOOKNAME => 4664;
use constant TWEI_CHAPTERNUMBER => 4665;
use constant TWEI_DOCUMENTNUMBER => 4666;
use constant TWEI_PAGENUMBER => 4667;
use constant TWEI_CAMERA => 4668;
use constant TWEI_FRAMENUMBER => 4669;
use constant TWEI_FRAME => 4670;
use constant TWEI_PIXELFLAVOR => 4671;
use constant TWEI_ICCPROFILE => 4672;
use constant TWEI_LASTSEGMENT => 4673;
use constant TWEI_SEGMENTNUMBER => 4674;
use constant TWEI_MAGDATA => 4675;
use constant TWEI_MAGTYPE => 4676;
use constant TWEI_PAGESIDE => 4677;
use constant TWEI_FILESYSTEMSOURCE => 4678;
use constant TWEI_IMAGEMERGED => 4679;
use constant TWEI_MAGDATALENGTH => 4680;
use constant TWEI_PAPERCOUNT => 4681;
use constant TWEI_PRINTERTEXT => 4682;
use constant TWEI_TWAINDIRECTMETADATA => 4683;
use constant TWEI_IAFIELDA_VALUE => 4684;
use constant TWEI_IAFIELDB_VALUE => 4685;
use constant TWEI_IAFIELDC_VALUE => 4686;
use constant TWEI_IAFIELDD_VALUE => 4687;
use constant TWEI_IAFIELDE_VALUE => 4688;
use constant TWEI_IALEVEL => 4689;
use constant TWEI_PRINTER => 4690;
use constant TWEI_BARCODETEXT2 => 4691;
use constant TWEJ_NONE => 0;
use constant TWEJ_MIDSEPARATOR => 1;
use constant TWEJ_PATCH1 => 2;
use constant TWEJ_PATCH2 => 3;
use constant TWEJ_PATCH3 => 4;
use constant TWEJ_PATCH4 => 5;
use constant TWEJ_PATCH6 => 6;
use constant TWEJ_PATCHT => 7;
use constant TWRC_CUSTOMBASE => 32768;
use constant TWRC_SUCCESS => 0;
use constant TWRC_FAILURE => 1;
use constant TWRC_CHECKSTATUS => 2;
use constant TWRC_CANCEL => 3;
use constant TWRC_DSEVENT => 4;
use constant TWRC_NOTDSEVENT => 5;
use constant TWRC_XFERDONE => 6;
use constant TWRC_ENDOFLIST => 7;
use constant TWRC_INFONOTSUPPORTED => 8;
use constant TWRC_DATANOTAVAILABLE => 9;
use constant TWRC_BUSY => 10;
use constant TWRC_SCANNERLOCKED => 11;
use constant TWCC_CUSTOMBASE => 32768;
use constant TWCC_SUCCESS => 0;
use constant TWCC_BUMMER => 1;
use constant TWCC_LOWMEMORY => 2;
use constant TWCC_NODS => 3;
use constant TWCC_MAXCONNECTIONS => 4;
use constant TWCC_OPERATIONERROR => 5;
use constant TWCC_BADCAP => 6;
use constant TWCC_BADPROTOCOL => 9;
use constant TWCC_BADVALUE => 10;
use constant TWCC_SEQERROR => 11;
use constant TWCC_BADDEST => 12;
use constant TWCC_CAPUNSUPPORTED => 13;
use constant TWCC_CAPBADOPERATION => 14;
use constant TWCC_CAPSEQERROR => 15;
use constant TWCC_DENIED => 16;
use constant TWCC_FILEEXISTS => 17;
use constant TWCC_FILENOTFOUND => 18;
use constant TWCC_NOTEMPTY => 19;
use constant TWCC_PAPERJAM => 20;
use constant TWCC_PAPERDOUBLEFEED => 21;
use constant TWCC_FILEWRITEERROR => 22;
use constant TWCC_CHECKDEVICEONLINE => 23;
use constant TWCC_INTERLOCK => 24;
use constant TWCC_DAMAGEDCORNER => 25;
use constant TWCC_FOCUSERROR => 26;
use constant TWCC_DOCTOOLIGHT => 27;
use constant TWCC_DOCTOODARK => 28;
use constant TWCC_NOMEDIA => 29;
use constant TWQC_GET => 1;
use constant TWQC_SET => 2;
use constant TWQC_GETDEFAULT => 4;
use constant TWQC_GETCURRENT => 8;
use constant TWQC_RESET => 16;
use constant TWQC_SETCONSTRAINT => 32;
use constant TWQC_GETHELP => 256;
use constant TWQC_GETLABEL => 512;
use constant TWQC_GETLABELENUM => 1024;
use constant TWTY_STR1024 => 13;
use constant TWTY_UNI512 => 14;
use constant TWFF_JPN => 12;
use constant DAT_TWUNKIDENTITY => 11;
use constant DAT_SETUPFILEXFER2 => 769;
use constant CAP_CLEARBUFFERS => 4125;
use constant CAP_SUPPORTEDCAPSEXT => 4108;
use constant CAP_PAGEMULTIPLEACQUIRE => 4131;
use constant CAP_PAPERBINDING => 4143;
use constant CAP_PASSTHRU => 4145;
use constant CAP_POWERDOWNTIME => 4148;
use constant ACAP_AUDIOFILEFORMAT => 4609;
use constant MSG_CHECKSTATUS => 513;
use constant MSG_INVOKE_CALLBACK => 2307;
use constant TWQC_CONSTRAINABLE => 64;
use constant TWSX_FILE2 => 3;
use constant TWFS_FILESYSTEM => 0;
use constant TWFS_RECURSIVEDELETE => 1;
use constant TWPT_SRGB64 => 11;
use constant TWPT_BGR => 12;
use constant TWPT_CIELAB => 13;
use constant TWPT_CIELUV => 14;
use constant TWPT_YCBCR => 15;
use constant TWSS_B => 8;
use constant TWSS_A4LETTER => 1;
use constant TWSS_B3 => 12;
use constant TWSS_B4 => 6;
use constant TWSS_B6 => 7;
use constant TWSS_B5LETTER => 2;
use constant TWAF_WAV => 0;
use constant TWAF_AIFF => 1;
use constant TWAF_AU => 3;
use constant TWAF_SND => 4;
use constant TWCB_AUTO => 0;
use constant TWCB_CLEAR => 1;
use constant TWCB_NOCLEAR => 2;

1;
