/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dynarithmic_DTwainJava */

#ifndef _Included_com_dynarithmic_DTwainJava
#define _Included_com_dynarithmic_DTwainJava
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    isTwainAvailable
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_DTwainJava_isTwainAvailable
  (JNIEnv *, jobject);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    sysInitialize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_DTwainJava_sysInitialize
  (JNIEnv *, jobject);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    sysDestroy
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_DTwainJava_sysDestroy
  (JNIEnv *, jobject);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    setLicense
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_DTwainJava_setLicense
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    setAppInfo
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_DTwainJava_setAppInfo
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    getAppInfo
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_DTwainJava_getAppInfo
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    setTwainMode
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_DTwainJava_setTwainMode
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    setCountry
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_DTwainJava_setCountry
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    setLanguage
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_DTwainJava_setLanguage
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    getLastError
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_DTwainJava_getLastError
  (JNIEnv *, jobject);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    getErrorString
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dynarithmic_DTwainJava_getErrorString
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    startTwainSession
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_DTwainJava_startTwainSession
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    endTwainSession
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_DTwainJava_endTwainSession
  (JNIEnv *, jobject);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    isAcquiring
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_DTwainJava_isAcquiring__
  (JNIEnv *, jobject);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    selectSource
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_DTwainJava_selectSource
  (JNIEnv *, jobject);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    selectSourceByName
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_DTwainJava_selectSourceByName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    selectDefaultSource
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_DTwainJava_selectDefaultSource
  (JNIEnv *, jobject);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    selectSourceEx
 * Signature: (Ljava/lang/String;III)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_DTwainJava_selectSourceEx
  (JNIEnv *, jobject, jstring, jint, jint, jint);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    getSourceProductName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dynarithmic_DTwainJava_getSourceProductName
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    getSourceProductFamily
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dynarithmic_DTwainJava_getSourceProductFamily
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    getSourceManufacturer
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dynarithmic_DTwainJava_getSourceManufacturer
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    getSourceMajorVersion
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_DTwainJava_getSourceMajorVersion
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    getSourceMinorVersion
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_DTwainJava_getSourceMinorVersion
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    getSourceVersionInfo
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dynarithmic_DTwainJava_getSourceVersionInfo
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    getAppProductName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dynarithmic_DTwainJava_getAppProductName
  (JNIEnv *, jobject);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    getAppProductFamily
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dynarithmic_DTwainJava_getAppProductFamily
  (JNIEnv *, jobject);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    getAppManufacturer
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dynarithmic_DTwainJava_getAppManufacturer
  (JNIEnv *, jobject);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    getAppVersionInfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dynarithmic_DTwainJava_getAppVersionInfo
  (JNIEnv *, jobject);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    getTwainMode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_DTwainJava_getTwainMode
  (JNIEnv *, jobject);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    getCountry
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_DTwainJava_getCountry
  (JNIEnv *, jobject);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    getLanguage
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_DTwainJava_getLanguage
  (JNIEnv *, jobject);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    getDTWAINMajorVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_DTwainJava_getDTWAINMajorVersion
  (JNIEnv *, jobject);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    getDTWAINMinorVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_DTwainJava_getDTWAINMinorVersion
  (JNIEnv *, jobject);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    getDTWAINVersionType
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_DTwainJava_getDTWAINVersionType
  (JNIEnv *, jobject);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    enumSources
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_com_dynarithmic_DTwainJava_enumSources
  (JNIEnv *, jobject);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    openSource
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_DTwainJava_openSource
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    closeSource
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_DTwainJava_closeSource
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    enumSupportedCaps
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_dynarithmic_DTwainJava_enumSupportedCaps
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    enumCustomCaps
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_dynarithmic_DTwainJava_enumCustomCaps
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    enumExtendedCaps
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_dynarithmic_DTwainJava_enumExtendedCaps
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    getCapFromName
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_DTwainJava_getCapFromName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    getCapArrayType
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_DTwainJava_getCapArrayType
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    getNameFromCap
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dynarithmic_DTwainJava_getNameFromCap
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    isCapSupported
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_DTwainJava_isCapSupported
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    getCapContainer
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_DTwainJava_getCapContainer
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    getCapValuesInt
 * Signature: (III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_dynarithmic_DTwainJava_getCapValuesInt
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    getCapValuesDouble
 * Signature: (III)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_dynarithmic_DTwainJava_getCapValuesDouble
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    getCapValuesString
 * Signature: (III)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_dynarithmic_DTwainJava_getCapValuesString
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    getCapValuesFrame
 * Signature: (III)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_dynarithmic_DTwainJava_getCapValuesFrame
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    setCapValuesInt
 * Signature: (II[III)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_DTwainJava_setCapValuesInt
  (JNIEnv *, jobject, jint, jint, jintArray, jint, jint);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    setCapValuesDouble
 * Signature: (II[DII)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_DTwainJava_setCapValuesDouble
  (JNIEnv *, jobject, jint, jint, jdoubleArray, jint, jint);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    setCapValuesString
 * Signature: (II[Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_DTwainJava_setCapValuesString
  (JNIEnv *, jobject, jint, jint, jobjectArray, jint, jint);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    setCapValuesFrame
 * Signature: (II[DII)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_DTwainJava_setCapValuesFrame
  (JNIEnv *, jobject, jint, jint, jdoubleArray, jint, jint);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    getBrightness
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_dynarithmic_DTwainJava_getBrightness
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    getResolution
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_dynarithmic_DTwainJava_getResolution
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    getContrast
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_dynarithmic_DTwainJava_getContrast
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    setBrightness
 * Signature: (ID)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_DTwainJava_setBrightness
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    setResolution
 * Signature: (ID)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_DTwainJava_setResolution
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    setContrast
 * Signature: (ID)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_DTwainJava_setContrast
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    enumBrightnessValues
 * Signature: (I)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_dynarithmic_DTwainJava_enumBrightnessValues
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    enumContrastValues
 * Signature: (I)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_dynarithmic_DTwainJava_enumContrastValues
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    enumResolutionValues
 * Signature: (I)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_dynarithmic_DTwainJava_enumResolutionValues
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    createRangeHandle
 * Signature: (IIIII)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_DTwainJava_createRangeHandle__IIIII
  (JNIEnv *, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    createRangeHandle
 * Signature: (DDDDD)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_DTwainJava_createRangeHandle__DDDDD
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    expandRangeInt
 * Signature: (Lcom/dynarithmic/DTwainRangeInt;)[I
 */
JNIEXPORT jintArray JNICALL Java_com_dynarithmic_DTwainJava_expandRangeInt
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    expandRangeDouble
 * Signature: (Lcom/dynarithmic/DTwainRangeDouble;)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_dynarithmic_DTwainJava_expandRangeDouble
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    getRangeCountInt
 * Signature: (Lcom/dynarithmic/DTwainRangeInt;)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_DTwainJava_getRangeCountInt
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    getRangeCountDouble
 * Signature: (Lcom/dynarithmic/DTwainRangeDouble;)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_DTwainJava_getRangeCountDouble
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    getNearestValue
 * Signature: (Lcom/dynarithmic/DTwainRangeInt;I)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_DTwainJava_getNearestValue__Lcom_dynarithmic_DTwainRangeInt_2I
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    getNearestValue
 * Signature: (Lcom/dynarithmic/DTwainRangeDouble;D)D
 */
JNIEXPORT jdouble JNICALL Java_com_dynarithmic_DTwainJava_getNearestValue__Lcom_dynarithmic_DTwainRangeDouble_2D
  (JNIEnv *, jobject, jobject, jdouble);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    getCapJavaArrayType
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_DTwainJava_getCapJavaArrayType__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    getCapJavaArrayType
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_DTwainJava_getCapJavaArrayType__II
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    isUIEnabled
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_DTwainJava_isUIEnabled
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    isUIOnlySupported
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_DTwainJava_isUIOnlySupported
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    isAcquiring
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_DTwainJava_isAcquiring__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    setCallback
 * Signature: (Ljava/lang/Object;Lcom/dynarithmic/DTwainInterface;)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_DTwainJava_setCallback
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    setTestCallback
 * Signature: (Ljava/lang/Object;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_DTwainJava_setTestCallback
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    acquireFile
 * Signature: (I[Ljava/lang/String;Lcom/dynarithmic/DTwainAcquireParams;)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_DTwainJava_acquireFile
  (JNIEnv *, jobject, jint, jobjectArray, jobject);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    acquireNative
 * Signature: (ILcom/dynarithmic/DTwainAcquireParams;Ljava/util/Vector;Ljava/util/Vector;)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_DTwainJava_acquireNative
  (JNIEnv *, jobject, jint, jobject, jobject, jobject);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    getAcquiredImage
 * Signature: (III)Ljava/awt/Image;
 */
JNIEXPORT jobject JNICALL Java_com_dynarithmic_DTwainJava_getAcquiredImage
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    setTwainLog
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_DTwainJava_setTwainLog
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    setWorkDirectory
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_DTwainJava_setWorkDirectory
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    createAcquisitionArray
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_DTwainJava_createAcquisitionArray
  (JNIEnv *, jobject);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    setPaperSize
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_DTwainJava_setPaperSize
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    setPDFOptions
 * Signature: (ILcom/dynarithmic/DTwainPDFOptions;)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_DTwainJava_setPDFOptions
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    enableIndicatorCall
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_DTwainJava_enableIndicatorCall
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    arrayCreate
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_DTwainJava_arrayCreate
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    arrayDestroy
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_DTwainJava_arrayDestroy
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    arraySetStringAt
 * Signature: (IILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_DTwainJava_arraySetStringAt
  (JNIEnv *, jobject, jint, jint, jstring);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    enableMessageNotify
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_DTwainJava_enableMessageNotify
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    getImageInfo
 * Signature: (ILcom/dynarithmic/DTwainImageInfo;)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_DTwainJava_getImageInfo
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    getCustomDSData
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_dynarithmic_DTwainJava_getCustomDSData
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    getAcquireStripSizes
 * Signature: (ILcom/dynarithmic/DTwainCompressedTransfer;)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_DTwainJava_getAcquireStripSizes
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    acquireCompressed
 * Signature: (ILcom/dynarithmic/DTwainCompressedTransfer;Lcom/dynarithmic/DTwainAcquireParams;)I
 */
JNIEXPORT jint JNICALL Java_com_dynarithmic_DTwainJava_acquireCompressed
  (JNIEnv *, jobject, jint, jobject, jobject);

/*
 * Class:     com_dynarithmic_DTwainJava
 * Method:    getAcquiredStripDataEx
 * Signature: (ILcom/dynarithmic/DTwainCompressedStripInfo;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_dynarithmic_DTwainJava_getAcquiredStripDataEx
  (JNIEnv *, jobject, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
