/* Project settings */
var hmAnimate = true;
var hmPopupSticky = true;
var hmImageLightbox = true;
var hmVideoLightbox = true;
var hmLightboxConstrained = true;
var hmForceRedirect = false;
var hmTocSingleClick = false;
var autocollapse = false;
var gaaccount = "";
var initialtocstate = "collapsed";
