msbuild dtwain_5_vs2015.sln /t:DTWAIN_DLL /t:%1 /property:Configuration=Win32_DTWAINDLL_D /property:Platform=Win32
msbuild dtwain_5_vs2015.sln /t:DTWAIN_DLL /t:%1 /property:Configuration=Win32_DTWAINDLL /property:Platform=Win32
msbuild dtwain_5_vs2015.sln /t:DTWAIN_DLL /t:%1 /property:Configuration=Win32_DTWAINDLL_U /property:Platform=Win32
msbuild dtwain_5_vs2015.sln /t:DTWAIN_DLL /t:%1 /property:Configuration=Win32_DTWAINDLL_U_D /property:Platform=Win32
msbuild dtwain_5_vs2015.sln /t:DTWAIN_DLL /t:%1 /property:Configuration=Win64_DTWAINDLL_D /property:Platform=x64
msbuild dtwain_5_vs2015.sln /t:DTWAIN_DLL /t:%1 /property:Configuration=Win64_DTWAINDLL /property:Platform=x64
msbuild dtwain_5_vs2015.sln /t:DTWAIN_DLL /t:%1 /property:Configuration=Win64_DTWAINDLL_U /property:Platform=x64
msbuild dtwain_5_vs2015.sln /t:DTWAIN_DLL /t:%1 /property:Configuration=Win64_DTWAINDLL_U_D /property:Platform=x64
msbuild dtwain_5_vs2015.sln /t:DTWDEMO /t:%1 /property:Configuration=Win32_DTWAINDLL_D /property:Platform=Win32
msbuild dtwain_5_vs2015.sln /t:DTWDEMO /t:%1  /property:Configuration=Win32_DTWAINDLL /property:Platform=Win32
msbuild dtwain_5_vs2015.sln /t:DTWDEMO /t:%1  /property:Configuration=Win32_DTWAINDLL_U /property:Platform=Win32
msbuild dtwain_5_vs2015.sln /t:DTWDEMO /t:%1 /property:Configuration=Win32_DTWAINDLL_U_D /property:Platform=Win32
msbuild dtwain_5_vs2015.sln /t:DTWDEMO /t:%1 /property:Configuration=Win64_DTWAINDLL_D /property:Platform=x64
msbuild dtwain_5_vs2015.sln /t:DTWDEMO /t:%1 /property:Configuration=Win64_DTWAINDLL /property:Platform=x64
msbuild dtwain_5_vs2015.sln /t:DTWDEMO /t:%1 /property:Configuration=Win64_DTWAINDLL_U /property:Platform=x64
msbuild dtwain_5_vs2015.sln /t:DTWDEMO /t:%1 /property:Configuration=Win64_DTWAINDLL_U_D /property:Platform=x64